### ISSUE TITLE
transforming external url

### ISSUE THREAD

**Issue by pioneerdesign** [spacecatninja/craft-imager-x#113]
### I'm submitting a... 
- [X ] general question
 
### Description
We're trying to transform a YouTube thumbnail image. I've verified the url to the image is valid but it doesn't seem to write the image locally. The generated transform show the full url to the image. We're also using imgix to handle transforms. 

Here's our code:
```
{% set youTubeThumb = 'https://i.ytimg.com/vi/{{ vid.id }}/mqdefault.jpg' %}
       {% set transformedYT = craft.imager.transformImage(youTubeThumb,  { width: 315, height: 175, interlace: true }) %}	  
        <img src="{{ transformedYT.url }}" loading="lazy" alt="{{ entry.title }}" class="videothumb">
```

### Displayed errors, stack trace, relevant logs  
Transformed url: https://xxx.imgix.net/https%3A%2F%2Fi.ytimg.com%2Fvi%2F%7B%7B%20vid.id%20%7D%7D%2Fmqdefault.jpg?crop=focalpoint&amp;fit=crop&amp;fp-x=0.5&amp;fp-y=0.5&amp;h=175&amp;q=80&amp;w=315

### Additional info

- Imager version & edition: Imager X 3.5.1
- Imager transformer: imgix
- Craft version: 3.7.7
- PHP version: 7.3

**Comment by aelvan** [comment]
Hi,

It sounds like you're trying to transform an external URL through an Imgix source that's not a "Web proxy" source. 

To be able to transform images _using a fully qualified URL_, you need to create a "Web proxy" source in Imgix, and indicate that a given profile in the imager config is a web proxy using the `sourceIsWebProxy` config setting.

In Imgix:

![CleanShot 2021-08-08 at 16 06 45](https://user-images.githubusercontent.com/2675644/128634784-6d1c9ebc-8264-40b5-9e4b-5e6e52b09e7a.png)

You could pass all images through the webproxy source, even if they're local to your server, but what you usually would want to do is set up one source for your main assets, and an additional for external images, like this:

```
'imgixConfig' => [
    'default' => [
        'domain' => 'imager.imgix.net',
        'useHttps' => true,
        'signKey' => 'XxXxXxXx',
        'sourceIsWebProxy' => false,
        'useCloudSourcePath' => true,
        'getExternalImageDimensions' => true,
        'defaultParams' => ['auto'=>'compress,format', 'q'=>80],
    ],
    'external' => [
        'domain' => 'imager-external.imgix.net',
        'useHttps' => true,
        'signKey' => 'XxXxXxXx',
        'sourceIsWebProxy' => true,
        'useCloudSourcePath' => true,
        'getExternalImageDimensions' => true,
        'defaultParams' => ['auto'=>'compress,format', 'q'=>80],
    ]
]
```

Then, in your template you can change the profile when necessary:

```
{% set transform = craft.imager.transformImage(externalUrl, { width: 400 }, {}, { imgixProfile: 'external' }) %}
```

Hope that helps, this is documented under [the imgixConfig config setting](https://imager-x.spacecat.ninja/configuration.html#imgixconfig-array) in the documentation.

**Comment by jamesmacwhite** [comment]
Just a note for anyone visiting this, Imgix Web Proxy source became an enterprise feature, so it's no longer generally available.

**Comment by aelvan** [comment]
@jamesmacwhite That's a bummer, Imgix is really tanking these days. 

For anyone looking for an alternative, [ImageKit](https://github.com/spacecatninja/craft-imager-x-imagekit-transformer) has support the same types of sources that Imgix had. 

Also note that you can use Imager's local transforms for external images, and Imgix for assets by overriding `transformer` at the template level: 

```
{% set transform = craft.imager.transformImage(externalUrl, { width: 400 }, {}, { transformer: 'craft' }) %}
```

You'd then miss the benefit of offloading the transform to Imgix and be back to transforming images on the server, but at least it's a rather low-effort way to keep things working.

**Comment by jamesmacwhite** [comment]
@aelvan Indeed, the organisation I work for is on a legacy plan and we are holding onto that plan until we are told we can't, because the newer plans are insanely more expensive for what we have now. Longer term we may remove Imgix and replace with something else. ImageKit is something I may look into longer term. Thank you for the tip.

The main reason for Imgix was removing/offloading the work from our web app, simply because we had multiple issues with transforms failing and causing a 500 error bringing down the front end of whatever entry the asset was linked to. Granted potentially more defensive coding might help, but the failing transforms is just something that isn't worth dealing with most of the time and in fairness Imgix is still great for it. This was a while ago, so with the improvements to queue handling and using console runners to offload it, it might be accept for some external URLs. 

On Imgix generally, It just looks like they've gone down a route that's geared towards enterprise or large usage clients. Back in the day they had pricing plans which were great for small usage, these have gone now, unless you happened to have a legacy plan!

The organisation I work for is a major college in the United Kingdom, but we don't have the budgets of the large enterprise clients ;), so it is a shame.
