### ISSUE TITLE
Letterbox Error - undefined color when using Imgix

### ISSUE THREAD

**Issue by terryupton** [spacecatninja/craft-imager-x#119]
- [x ] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
I have the following setup as a name transform:
```
  'logo' => [
    'displayName' => 'Logo',
    'transforms'  => [
      ['width' => 150],
      ['width' => 200],
      ['width' => 300],
      ['width' => 400],
    ],
    'defaults'    => [
      'ratio'     => 1 / 0.66,
      'mode'      => 'letterbox',
      'letterbox' => [
        'color:'  => '#FFF',
        'opacity' => 0
      ],
    ],
  ],
```

When I try and use this with Imgix I get the following error:
`Undefined index: color`
<img width="1744" alt="Screenshot 2021-09-29 at 11 39 00" src="https://user-images.githubusercontent.com/5698596/135253363-7626dd1a-5390-4db6-8424-25b85a910129.png">

If I use this with 'craft' transforms then it works just fine.
If I remove the letterbox settings from the transform, then it also works ok, but obviously, it does't apply those settings.

**Comment by aelvan** [comment]
If you actually have `color:` in the letterbox definition, that's the error. It should be `color`.

The reason why you only get this error for the Imgix transformer, is that there's some extra error checking in the Craft one, so it will fall back to #000 if color is not set. Which you wouldn't see in this case, because opacity is 0.

**Comment by terryupton** [comment]
Doh! Sorry @aelvan - thanks for spotting that.
