### ISSUE TITLE
Question on migrating/reindexing transformed images

### ISSUE THREAD

**Issue by mattbloomfield** [spacecatninja/craft-imager-x#128]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
I'm trying to figure out how to handle the massive number of transforms we are working with on our site. Each image generates about 30 transforms for business reasons. These are stored in an s3 bucket. I want to be able to copy these transformed images down to my dev/staging buckets and have Craft know about them - basically index those transformed images so they don't have to be re-generated for each environment. 

I can obviously copy them just fine - but I'm not sure how to re-index them. Is this something imager-x has a command for that I'm missing? I haven't figured out how it identifies the need to create a transform vs load an existing transform. Any tips you can offer would be awesome. 

### Additional info

- Imager version & edition: v3.5.4 (Pro)
- Imager transformer: idk
- Craft version: Craft Pro 3.7.25.1
- PHP version: 7.4.23
- Image driver & version: GD 7.4.23
- Database driver & version: MySQL 5.5.5
- Plugins & versions (if relevant):

![image](https://user-images.githubusercontent.com/37582550/145258672-ce8ae93b-5baf-4739-a6e3-a59e5388ca36.png)

**Comment by aelvan** [comment]
Hi,

Imager only use the files in the imagerSystemPath to determine if a transform is made, and if it need to be recreated (if the timestamp is older than the cache duration). So you should be able to just copy the files from the S3 bucket, or the imagerSystemPath on your server, into your local imagerSystemPath. Unless you've configured [filenamePattern](https://imager-x.spacecat.ninja/configuration.html#filenamepattern-string), or any of the other settings for customizing paths and filenames, _differently between your environments_, Imager should pick up on what's been transformed, and serve those instead of generating new ones. 

Also, if you don't need the actual images, you can use the [`mockImage`](https://imager-x.spacecat.ninja/configuration.html#mockimage-int-string-asset) config setting to just replace all images with a placeholder one. Often this is good enough for development, and lets you avoid having to sync huge amounts of images to your local env.

**Comment by mattbloomfield** [comment]
Yes, very helpful. Let me just make sure I understand... 

### Caveats
* I am not using filenamePattern on any environment
* I am relying on the default for imagerSystemPath
* Using mockImage unfortunately won't meet our needs on this setup.

So after I copy the transformed images from my prod S3 bucket down to, say, my staging S3 bucket, I need to: 

1. Copy all the cached images in the production FS to the staging FS 

And that's it? So imagerx is not relying on any type of database or json but actually doing and FS lookup to ensure the transform exists, then supplying an S3 URL to Craft to use on the frontend?

**Comment by aelvan** [comment]
Yeah, no database, json or index of any kind, it only checks if a transform exists inside the `imagerSystemPath`. So yeah, just sync your file systems and buckets, and you should be golden.

**Comment by mattbloomfield** [comment]
Awesome! Thank you!! So, so helpful!
