### ISSUE TITLE
Does Imager check source width before generating transforms now?

### ISSUE THREAD

**Issue by terryupton** [spacecatninja/craft-imager-x#13]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x ] general question

### Description
In 'Original' Imager, I used to have a check that I ran before setting the widths in the transform object.
Like so:
```
  {% for width in widths %}
    {% if (image.width > width) %}
      {% set imageSizes = imageSizes|merge([{ 'width': width }]) %}
    {% endif %}
  {% endfor %}
```

This was necessary as it stopped duplicate versions of an image being created at each width specified if the image used wasn't large enough. Here is the original thread.
https://github.com/aelvan/Imager-Craft/issues/158

I wanted to ask if this is now fixed in ImagerX or would I still need to run these checks, I am more interested in how this works and if it is resolved when using automatic generation of transforms via config file. I have a current build I am working on that is quite image heavy and I want to offload the images being transformed on the front-end (first load) as it sometimes causes a time-out or at least to make it a little more performant none-the-less.

**Comment by aelvan** [comment]
Hi Terry,

No, this has not changed since Imager "Vanilla".

But this got me looking into what one would do to achieve the same thing you're doing in your templates, in a [named transform](https://imager-x.spacecat.ninja/usage/named-transforms.html). Turned out I needed to implement a small fix (v3.0.5), but you can now use a combination of callables and `fillTransforms` to achive it, like this:

```
    'heroImage' => [
        'transforms' => [
            ['width' => 800],
            ['width' => static function ($image) {
                if ($image instanceof \craft\elements\Asset) {
                    return min($image->getWidth(), 2000);
                }
                return 2000;
            }],
        ],
        'defaults' => [
            'ratio' => 16/9,
            'jpegQuality' => 80
        ],
        'configOverrides' => [
            'fillTransforms' => true,
            'fillInterval' => 300,
        ]
    ],
```

So, for the second size in my transforms, I've added a callable that, if the image that's passed in is an Asset, returns the with of the asset if it's smaller than 2000px, if not it returns 2000px (you'll probably want to put a cap on most transforms I'm guessing). With `fillTransforms` and `fillInterval` set, it will then fill in the missing sizes between these points, but you'll never get a size that's bigger than the assets.

Maybe you'll also want to add something for checking if the asset is smaller than your minimum size, but I'll leave that up to you to add if needed. :)

Hope this helps!
