### ISSUE TITLE
Imager Runtime directory filling up disk VERY quickly

### ISSUE THREAD

**Issue by GaryReckard** [spacecatninja/craft-imager-x#142]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. Have lots of assets
2. Configure something wrong...
3. Have your `/storage/runtime/imager/` directories use up all the space on your server

### Description
I'm not sure when this started being an issue, but at some point in the past 6 months, possibly after an upgrade of Craft and plugins, I started noticing that it took a long time to clear caches. Our `/storage/runtime` directory was always rather large, and on several occasions, has filled up all usable space on our server, causing a host of issues on the website.

Just this morning, I removed the `runtime` directory entirely, and within 10 minutes it had reached almost 2 gigs.

Do I perhaps have something configured wrong? Is there a way to prevent imager from filling up my disk? 

**Thanks**

### Additional info

- Imager version & edition: v3.5.5
- Imager transformer: ?
- Craft version: 3.7.27.2
- PHP version: 7.3.21
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.9.11-60)
- Database driver & version: MySQL 5.6.47.0
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Hi!

The things that are stored in the runtime folder are:

- Local copies of images on external volumes (S3, GCS, or similar) 
- Local copies of external images (ie when passing in an URL instead of an Asset)
- Temporary files that are created when using custom encoders (for creating webp, avif or jpeg-xl images when the driver doesn't have support)

The first two can be disabled by setting `cacheRemoteFiles` to `false`. This will of course have an impact on performance, since Imager will have to download the image every time it needs to do a transform, so depending on your project this may/may not be a good idea.

The temporary files should be deleted automatically after Imager is done with them. There was a bug that was introduced in 3.5.0 that would make webp conversions using the old `cwebp` setup fail, resulting in temporary files being left in the `storage/runtime/imager/temp` folder. But this error should've been fixed in 3.5.4. 

To further debug the following would help to know:

- Which folders do you have inside `storage/runtime/imager`, and which ones grow big (try running `du -d1 -h` inside it)?
- If you enable the debug toolbar, are there any error messages when doing a transform (make sure the transform you're testing isn't cached)?
- Could you provide your Imager config (make sure to redact any sensitive data)?

**Comment by aelvan** [comment]
@GaryReckard Were you able to resolve this?

**Comment by StijnCoolen** [comment]
Hi @aelvan how does the` /storage/runtime/imager/` folder compare to the `/web/imager` folder, should both exist? Are both used to determine if a transform exists?

**Comment by aelvan** [comment]
Hi,

Both should exist, but they have different purpose. `/web/imager` is where the transformed files are stored, and this acts as the cache. The `/storage/runtime/imager/` folder are for temporary files that are needed to generate the transforms, primarily what I write above:

```
* Local copies of images on external volumes (S3, GCS, or similar)
* Local copies of external images (ie when passing in an URL instead of an Asset)
* Temporary files that are created when using custom encoders (for creating webp, avif or jpeg-xl images when the driver doesn't have support)
```

So emptying that folder will not immediately impact performance in any way, but if a transform cannot be found (it's new, or the cache was emptied/expired) and the source image is not stored locally, it needs to be downloaded before it can be transformed.
