### ISSUE TITLE
Display densities?

### ISSUE THREAD

**Issue by bransinanderson** [spacecatninja/craft-imager-x#160]
v4.1.1 - Pro
Craft 4.1.3

Using your plugin with Imgix. How can I use your plugin with display densities?
https://docs.imgix.com/tutorials/responsive-images-srcset-imgix

```
srcset="{{ craft.imager.srcset(transformedImages) }}"
```

I'd imagine most devices are at least 2x display density now, but say I still want to support 1x density. Given that `{{ craft.imager.srcset(transformedImages) }}` outputs the srcset list, I don't see a way to define or output display density. Kind of shocked as an image plugin, it's not listed anywhere in your documentation and I'm left wondering if it's even supported.

**Comment by bransinanderson** [comment]
> It's much more future proof to just supply the browser with a set of images of different widths, and let the browser decide which one is the best fit for a given screen

The issue we're finding with this approach is that an iPhone 12 resolution of 390 in width, the browser is picking a higher resolution e.g. 1024 with a different aspect ratio that is meant more for a tablet. **This is causing focal points you set in Craft to be inaccurate** because the browser is picking an image with a different aspect ratio meant for a tablet.

**Comment by aelvan** [comment]
You should never have images that are art-directed (ie have different aspect ratios) inside a srcset. That's what <picture> are for. Images in a src set should always be a set of images that are interchangeable with each other, it should never matter which one the browser picks. 

But again, you're free to generate the images you need yourself, and construct whatever markup you want, but there's nothing in Imager that encourages this.

**Comment by bransinanderson** [comment]
Thank you for quick response. Will revisit with `<picture>` element.

**Comment by bransinanderson** [comment]
> You should never have images that are art-directed differently (ie have different aspect ratios) inside a srcset.

Why be authoritative and say this? What is the hindrance?

**Comment by aelvan** [comment]
> Why be authoritative and say this?

I'm not sure of the nuances of "being authoritative" in this case, english is not my native language, so things sometimes get lost in translation. My intention was just to convey that images that are art-directed differently, are not suppose to be in the same srcset. That's just not how a srcset is suppose to be used. 

> What is the hindrance?

The thing you describe, where you make assumptions as to what image in the set the user will see ("If the screen is 390px wide, the 1024px image surely will not be displayed"). It's up to the browser to pick one, so all the images in the srcset has to be possible candidates to display. If there are images in the srcset that should only show up above a certain breakpoint for instance (which is how I interpreted "...the browser is picking a higher resolution e.g. 1024 with a different aspect ratio that is meant more for a tablet."), it should be two different sets, inside a `<picture>` element, with appropriate media queries.

> Asking because the image tag seems to conjure up some new rule every year - and belief boils down to some blog that we've read without questioning why.

The specs haven't changed since 2014. I agree that there's a lot of bad advice out there, but I don't agree with your implication that this is my "belief". I base this on my knowledge of the W3C specs, articles from various sources (as I said, [the one I linked to](https://ericportis.com/posts/2014/srcset-sizes/) still describes this the best), and 20+ years of experience as a web developer (although only nine of those with responsive images). I feel like I should be able to give advice based on that, and not be thrown off as someone who just read a blog post "without questioning why".  

I did the exact same mistake you're describing (having images with different aspect ratios inside a srcset) when I started using it, everyone's probably been there. That's no reason to not be open for learning.

> Doing this for a number of years I am generally curious, and I'm wondering if you considered all possibilities on how others work with your plugin.
> ...best you make it in a flexible way and not dictate constrictive ways of using it. 

Imager is made to be an open-ended, non-opinionated and flexible toolbox for transforming, optimising and manipulating images. It's _not_ made to be a turnkey solution that "solves" responsive images for you automatically (there are other plugins that propose to do that). It assumes that the developer understands how responsive images in HTML work (if that's what the goal of using Imager is), and this is very much in line with the whole philosophy of Craft, as opposed to other CMS' like Wordpress. 

`craft.imager.srcset()` is one of the few built-in helpers (in addition to various placeholder helpers) that actually _outputs_ something, instead of just providing the developer with the raw data. Maybe I should just have left that out too, and let developers make their own macros/loops, but from what I gather most people, including myself, find it quite useful, so there it is. 

The reason why it is there, and only use the width/height descriptors, is exactly for the reasons you mention. The width and height descriptors are _unambiguous_. There are no assumptions baked in about how the srcset is constructed, it's a strictly data-based string that lists some images, and indicate their width or height. How developers end up using this string is up to them, it can be used on a `<img>` or `<source>` tag, or as part of a bgset. Doesn't matter, there's no difference the nature of the string makes it work everywhere.

Abstract that with the `x` descriptor. Let's say you have a list of transformed images; what's the base size that should be used to calculate the descriptors? The first image in the set? What if it's reversed, some developers may like to list their image sizes from biggest to smallest. That would mean that the first image would be 1x, the next 0.6x, and so one. And what if a developer doesn't want to have the 1x image in there at all, and instead just have 2x, 2.5x, 3x and 4x? How would one cater to that? I could surely bake in _something_ that does this, but it's already more opinionated and less flexible, which is the opposite of what you're asking for. And when the alternative is something like this, it seems a complete waste:

``` 
{% set transforms = craft.imagerx.transformImage(image, [{ width: 400 }, { width: 800 }, { width: 1200 }]) %}
<img ... srcset="{{ transforms[0].url }} 1x, {{ transforms[1].url }} 2x, {{ transforms[2].url }} 3x">
```

> You make an image plugin for the community, cash-in money...

This is totally besides the point, and also totally unreasonable.

I've made and maintained tens of FOSS plugins for Craft CMS all the way back to Craft 1.0. For years Imager was a free plugin that I maintained, developed and supported, and poured a lot of effort into. I've been one of the most active advocates for keeping as much of the Craft eco-system (ie plugins and learning resources) as possible open and free, to encourage sharing, learning and lowering the threshold for people to buy into _Craft itself_. 

Since the launch of the plugin store, the environment for FOSS plugin developers got increasingly toxic, with open harassment of anyone suggesting using free plugins, and a general consensus in the community that "paid plugins are good, free plugins are shit". As much as I detest that notion, and think it's mostly propaganda from the paid-plugin community (and P&T itself which makes a cut), I decided that enough is enough. Instead of just retiring all of my plugins, I decided to pour that effort into building Imager X (with a ton of improvements and extra features) as a paid plugin, and spend my time on supporting and maintaining it.  

It's not up to me to judge if I'm successful or not, but I generally receive very little of the flaming criticism that you offer, very few bug reports, and had Craft 4 versions of all Imager plugins available the day that Craft 4.0 dropped. And you got 
a reply to your issue within an hour of it being posted. So I must be doing something right.

> The plugin and documentation is already behind on the times. Step it up.

I appreciate any constructive feedback on how to improve the documentation (like some of the things you edited out of your original post), but without the condescending snark.

**Comment by iuscare** [comment]
Even if it is a little bit off topic, I just wanted to say that I am completely disagree with the opinion of the OP. In fact @aelvan does a great job. In this particular case he even indicates a solution in his very first reply, which could solve the question of the OP just the way he wanted it to be by using the dpr parameter. Imager is a toolbox and a swiss knife for handling images in a flexible way which makes working with responsive images so much easier. With imageoptimize it has become some kind of industrial standard in the craft ecosystem. With the additional fast and helpful support I am very happy to pay for this

**Comment by bransinanderson** [comment]
First, I am saying sorry to @aelvan for coming across as rather harsh with my criticisms. At the time and my mood, I felt like a good harsh push with words was a necessity - turns out we are all a little sensitive with the things we create. I understand you've put your life into this plugin and also made some money from it too.

I hope you understand there is an entire industry of developers that have no choice, or sway in the matter of a design. We have no say over perfect aspect ratios. We are handed off a design, and to make it work under a deadline. Aspect ratios, screen widths, various hero heights that change based on content.

I'm baffled that your plugin, and documentation doesn't address anything related to various aspect ratios and media queries and seems rather out of touch on how the industry works currently.

I've made attempts of passing my own media query arrays with each transform width with your plugin. I cannot access them on output via Twig because they return as protected. Maybe something you could add to your documentation.

What I ended up doing is taking each post transform in a loop, and then merging into my own media min/max array to perform the transforms foreach picture > source tag. Kind of bonkers that the plugin addresses the perfectly formed srcset output but doesn't allow you to pass any kind of parameters for each transform.

If so, I'd like to see updated documentation on how to access that via Twig.

**Comment by aelvan** [comment]
> At the time and my mood, I felt like a good harsh push with words was a necessity - turns out we are all a little sensitive with the things we create.

That rarely is a good strategy if you want people to help you.

> I hope you understand there is an entire industry of developers that have no choice, or sway in the matter of a design. We have no say over perfect aspect ratios. We are handed off a design, and to make it work under a deadline. Aspect ratios, screen widths, various hero heights that change based on content.

I understand, since I'm one of those developers.

The rest of your post makes absolutely no sense, I have no idea what you're trying to do and how. Maybe a description of what you're trying to achieve, and examples of the code you have tried, would help.

**Comment by bransinanderson** [comment]
See. You've given up already - because I think you were offended.

**Comment by bransinanderson** [comment]
Creators these days can't accept harsh criticism. Like the good criticism they need to improve their product. You know the boss that lights the fire beneath you? You no longer have that. Especially in the dev world.

**Comment by aelvan** [comment]
So you didn't actually want help with your problem? You just wanted to be angry with the world?

Listen, I feel like a good harsh push is in order here. You don't strike me as a very good web developer. It's clear from what you're writing here that you don't understand responsive images, and you're not very good at problem solving. Instead of spending your time criticising others, maybe you should spend that time improving your skills. I see that your self-employed, maybe you need someone to light a fire beneath you?

**Comment by aelvan** [comment]
> My previous post mentioned your plugin doesn't provide the means to pass in any additional data (array) with each transformation and have access to that via Twig.

Yeah, I don't understand what you're trying to do. You want to pass in some arbitrary data with each transform, which is not used for anything, just passed back to the template? To what end?

> I don't think you build and work with websites regularly where you're disconnected from the design team. You're a tool guy - I get it.

You're wrong. For 20 years I've have been, and are, working in an agency-setting where I get design handed off from designers and mostly have to make the best of it. I make tools for exactly that setting.

**Comment by bransinanderson** [comment]
> Yeah, I don't understand what you're trying to do. You want to pass in some arbitrary data with each transform, which is not used for anything, just passed back to the template? To what end?

Why so snobby? I'm trying to understand on your part why this isn't necessary? Say I want a value thrown down on a class attribute?

I think what you're failing to understand is that widths of transformed images, do not translate to picture tag media queries of min/max and when they should be served to the user. Foreach transformed width, I want screen widths too.

**Comment by aelvan** [comment]
> I'm trying to understand on your part why this isn't necessary?

I'm not saying it isn't necessary, I just don't understand what you're trying to do.

> Say I want a value thrown down on a class attribute?

Like, a class attribute on an img tag? Imager doesn't output any markup, you can just add that directly in twig.

> I think what you're failing to understand is that widths of transformed images, do not translate to picture tag media queries of min/max and when they should be served to the user. 

That, I understand. What I don't understand is what you're trying to achieve. What's the markup that you want to end up with?

**Comment by bransinanderson** [comment]
> Like, a class attribute on an img tag? Imager doesn't output any markup, you can just add that directly in twig.

No, a value for a class, for a specific transform.

Visit foxnews dot com and look at their main headline image. Make that work using your plugin, and good luck - because you can't without trickery and array merging with those picture sources.

**Comment by aelvan** [comment]
This thing? 
![CleanShot 2022-08-18 at 16 11 47](https://user-images.githubusercontent.com/2675644/185416539-75cc5a61-fd49-421b-becb-7d185c22c38c.png)

**Comment by bransinanderson** [comment]
Yeah. Pay attention to those image sizes. In addition to the min and max widths set for each one.

**Comment by aelvan** [comment]
Cool, this is an excellent example of how _not_ to do responsive images, what a great _learning opportunity_!

If you really wanted to make something like this, I'd probably just do all the transforms in one go, and just map each of them to the markup. After all, there's nothing dynamic or scalable about that markup. So something like this:

```
{% set transforms = craft.imagerx.transformImage(asset, [
    { width: 320, ratio: 16/9 },
    { width: 640, ratio: 16/9 },
    { width: 480, ratio: 16/9 },
    { width: 960, ratio: 16/9 },
    { width: 768, ratio: 2.4 },
    { width: 1536, ratio: 2.4 },
    { width: 1024, ratio: 2.4 },
    { width: 1280, ratio: 2.4 },
]) %}

<picture>
    <source media="(min-width: 320px) and (max-width: 479px)" srcset="{{ transforms[0] }}, {{ transforms[1] }} 2x">
    <source media="(min-width: 480px) and (max-width: 767px)" srcset="{{ transforms[2] }}, {{ transforms[3] }} 2x">
    <source media="(min-width: 768px) and (max-width: 1023px)" srcset="{{ transforms[4] }}, {{ transforms[5] }} 2x">
    <source media="(min-width: 1024px) and (max-width: 1279px)" srcset="{{ transforms[6] }}">
    <source media="(min-width: 1280px)" srcset="{{ transforms[7] }}">
    <img src="{{ transforms[7] }}" width="1280" height="533">
</picture>
```

But as I said, this is not how you're suppose to do responsive images. Just the use of both min- and max-width is a give-away that this is made by someone who doesn't have a clue. Just by reversing the order of the sources, you can remove the max-width, the way picture+source works is that the first match is used. This would give the exact same result:

```
<picture>
    <source media="(min-width: 1280px)" srcset="{{ transforms[7] }}">
    <source media="(min-width: 1024px)" srcset="{{ transforms[6] }}">
    <source media="(min-width: 768px)" srcset="{{ transforms[4] }}, {{ transforms[5] }} 2x">
    <source media="(min-width: 480px)" srcset="{{ transforms[2] }}, {{ transforms[3] }} 2x">
    <source media="(min-width: 320px)" srcset="{{ transforms[0] }}, {{ transforms[1] }} 2x">
    <img src="{{ transforms[7] }}" width="1280" height="533">
</picture>
```

The next thing that's stupid (except if you actually want to serve crappy quality images to your users) is how the image sizes are locked to the lowest possible resolution. The image that is served to users who match the `(min-width: 320px) and (max-width: 479px)` media query, will always be 320px wide for 1x devices, and 640px for 2x or higher. Which will result in images that are always being scaled up. That's the completely opposite of what you want if you care about delivering good quality images.

In addition to that, on large screens (1024px and up), the fixed size images are much bigger than what they need to be.

And again, what I stressed earlier in this thread, they're assuming the only pixel densities that exist in the world is 1x and 2x. Which was basically only true right after iphone 4 was released in 2010, phones soon started to get a ton of different pixel densities.

**Luckily, there is a solution for this mess! [`sizes`+`srcset`](https://ericportis.com/posts/2014/srcset-sizes/)!**

But, first we need to understand the attributes of this particular image, and how it behaves responsively. These are the facts:

- Below (browser widths of) 768px it has an aspect ratio of 16/9, above it's 12/5 (or 2.4).
- Below 1024px the image is 100vw.
- Above 1024px it's 100vw minus the side columns which adds up to 488px.
- Above 1280px it's 100vw minus the side columns which adds up to 600px.
- Above 1440px the content container gets a fixed width of 1440px, making the image in question a fixed 766px.

That is all we need to know. In the real world I would've ignore the last two points, because they doesn't matter much, but for the sake of completeness, I'll include them here.

So, to begin with, I'd just create a series of images in different sizes for the two different aspect ratios:

```
{% set transformsSmall = craft.imagerx.transformImage(asset, [
    { width: 320, ratio: 16/9 },
    { width: 1120, ratio: 16/9 },
], { ratio: 16/9 }, { fillTransforms: true, fillInterval: 80 }) %}    

{% set transformsLarge = craft.imagerx.transformImage(asset, [
    { width: 750, ratio: 2.4 },
    { width: 1450, ratio: 2.4 },
], { ratio: 16/9 }, { fillTransforms: true, fillInterval: 100 }) %}    
```

I haven't given a lot of thoughts to the actual widths, obviously there are some magic widths that would result in perfect matches (like 766px for 1x desktops). Adjust accordingly.

Next, we'll build up the picture tag based on the requirements at the top.

```
<picture>
    <source media="(min-width: 1440px)" sizes="766px" srcset="{{ transformsLarge | srcset }}">
    <source media="(min-width: 1280px)" sizes="calc(100vw - 600px)" srcset="{{ transformsLarge | srcset }}">
    <source media="(min-width: 1024px)" sizes="calc(100vw - 488px)" srcset="{{ transformsLarge | srcset }}">
    <source media="(min-width: 768px)" sizes="100vw" srcset="{{ transformsLarge | srcset }}">
    <source media="(min-width: 320px)" sizes="100vw" srcset="{{ transformsSmall | srcset }}">
    <img src="{{ transformsSmall[0] }}" width="1280" height="533">
</picture>
```

As I said, I don't consider the top two sources very important, removing them will result in slightly bigger images being returned on sizes above 1280px, but that's not where you'd normally spend a lot of time optimizing for. Then again, it's like 1 min extra work, so..

The whole thing for reference:

```
{% set transformsSmall = craft.imagerx.transformImage(asset, [
    { width: 320, ratio: 16/9 },
    { width: 1120, ratio: 16/9 },
], { ratio: 16/9 }, { fillTransforms: true, fillInterval: 80 }) %}
    
{% set transformsLarge = craft.imagerx.transformImage(asset, [
    { width: 650, ratio: 2.4 },
    { width: 1450, ratio: 2.4 },
], { ratio: 16/9 }, { fillTransforms: true, fillInterval: 100 }) %}    
    
<picture>
    <source media="(min-width: 1440px)" sizes="766px" srcset="{{ transformsLarge | srcset }}">
    <source media="(min-width: 1280px)" sizes="calc(100vw - 600px)" srcset="{{ transformsLarge | srcset }}">
    <source media="(min-width: 1024px)" sizes="calc(100vw - 488px)" srcset="{{ transformsLarge | srcset }}">
    <source media="(min-width: 768px)" sizes="100vw" srcset="{{ transformsLarge | srcset }}">
    <source media="(min-width: 320px)" sizes="100vw" srcset="{{ transformsSmall | srcset }}">
    <img src="{{ transformsSmall[0] }}" width="1280" height="533">
</picture>
```

The result is a solution that will give the end users much more optimized images of much better quality. It's future proof because it doesn't make any assumptions about the device that user has, and what preferences he has regarding image loading. Someone width a 360px screen with 3x dpi and highspeed internet will get the super hires image that's 1120px, and a guy on a slow connection that has turned on bandwidth saving will maybe get the 320px one even if he has a phone that's 480px wide. Or the 480px one when he's on a fast connection again.

So, now that you've got both a solution for the wrong way of doing this, _and_ the correct one, does that clarify things for you?

**Comment by aelvan** [comment]
Hi, sorry for the late reply.

My _very static example_ was based on the limited information you gave about wanting to recreate _one specific piece of markup_. You gave no more information about how this was suppose to fit into a larger context, what dynamic behaviour you wanted to add and no example of the code that you had tried. That would have been useful to have in the very first post. 

You also seem to wilfully ignore the points about this being a sub-par/incorrect way of doing responsive images, as I've described in detail above. I don't understand why you choose to not take advice of any sort, and instead insist of continuing the way you did, even though you're obviously running into issues with it. It doesn't make me angry, just sad.

I'll continue working on the documentation, which was my reason for keeping this issue open, but I will never add information about how to do the things you're trying to do here, so it'll probably never be sufficient for you anyway. 

As to the point of passing some arbitrary data through Imager that you can pick up in your templates; it's a bad idea and will never happen. It would open up a huge can of worms in terms of maintainability and security, hence you can't do that anywhere else in the Craft eco system. What you're proposing would be just as "useful" for all of Craft's content API's. Say you want to create a list of entries where, you might think that it would be useful to send in some arbitrary data to `craft.entries` so that you could read them out inside an entry listing, ie:

```
{# Somewhere #}
{% set entries = craft.entries.section('mySection').class('my-class').limit(30).all() %}

{# Somewhere else #}
{% for entry in entries %}
    <div class="{{ entry.class }}">
        {{ entry.title }}
    </div
{% endfor %}
```

This is not the way.

I'll leave it at that, further discussions seems futile. Don't be angry, I'm only trying to help.
