### ISSUE TITLE
Can I pass "watermark" as parameter to @imagerTransform directive in GraphQL ?

### ISSUE THREAD

**Issue by diter14** [spacecatninja/craft-imager-x#162]
- [ ] bug report
- [ ] feature request
- [x] general question

### Description
Hey Guys! I'm using `@imagerTransform` directive and I'd like to know if is there a way to pass `watermark` (and its settings) as parameter to transform my Asset Images.

I'm trying something like this:
```
...
image {
    id
    url @imagerTransform (width: 300, format: "jpg", watermark: {
        image: "http://storage.googleapis.com/cdn.undiario.pe/articulos/un-cover-image-light.png", 
        width: 200, 
        height: 80, 
        position: { left: 100, top: 250 }, 
        opacity: 0.5, 
        blendMode: "multiply"
    })
}
...
```

But I'm getting an error:
```
"Unknown argument \"watermark\" on directive \"@imagerTransform\"."
```

Considering the message I'm assuming it's not possible but maybe is it in the roadmap? 

I'd appreciate some sugestions

Have a nice day!

**Comment by aelvan** [comment]
Hi,

To add watermarks, you need to use a [named transform](https://imager-x.spacecat.ninja/usage/named-transforms.html), and pass its handle through the `handle` argument.

So you could have a `imager-x-transforms.php` config file with something like this:

```
<?php

return [
    'watermarkedImage' => [
        'transforms' => [
            'width' => 300,
            'format' => 'jpg',
            'watermark' => [
                'image' => "http://storage.googleapis.com/cdn.undiario.pe/articulos/un-cover-image-light.png",
                'width' => 200,
                'height' => 80,
                'position' => ['left' => 100, 'top' => 250],
                'opacity' => 0.5,
                'blendMode' => "multiply"
            ]
        ]
    ],
```

And then in your GQL:

```
image {
    id
    url @imagerTransform (handle: 'watermarkedImage')
}
```

Just make sure that the code will actually produce output, in the example you gave, if the image isn't tall enough, the watermark may be outside of the image itself (because of the `top: 250` part). ;)

Hope that helps?

**Comment by diter14** [comment]
Thanks a lot! That was I needed.

I appreciate your help!

I'll close the issue.
