### ISSUE TITLE
Argument #1 ($images) must be of type array, null given

### ISSUE THREAD

**Issue by aaronrobb** [spacecatninja/craft-imager-x#177]
### I'm submitting a... 

- [ X ] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Update to Craft 4

### Description
 
After updating to Craft 4, we get the error below on a page that uses imager.
The error log shows it is erroring at the ```source.transform|merge({ format: format, }),``` line.

### Displayed errors, stack trace, relevant logs  

```
spacecatninja\imagerx\variables\ImagerVariable::srcset(): Argument #1 ($images) must be of type array, null given, called in /srv/dev.mysite.com/vendor/twig/twig/src/Extension/CoreExtension.php on line 1607
```
Our code causing the error:
```
{% for source in sources %}
          <source
            {{ lazyLoad ? 'data-' }}srcset="{{ craft.imager.srcset(craft.imager.transformImage(
              asset,
              [
                source.transform|merge({ format: format, }),
              ],
            )) }}"
            {{ (source.media ?? false) ? "media=\"#{source.media}\""|raw }}
            {{ format ? "type=\"image/#{format}\""|raw }}
          >
        {% endfor %}
```

### Additional info

- Imager version & edition: 4.1.6
- Imager transformer:
- Craft version: Craft Pro 4.2.5.2
- PHP version:  8.0
- Image driver & version:

**Comment by aelvan** [comment]
Hi,

This is due to stricter typing in 4.x. I've eased it in 4.1.7 to allow null to be passed to srcset (it will return an empty string), but the underlying issue here is that the `craft.imager.transformImage` in your code for some reason returns null. It's probably a good idea to code more defensively and make sure that this is handled before trying to pass the value to `craft.imager.srcset`, but with the change I just implemented, at least the code won't throw an error.
