### ISSUE TITLE
Blurhash thingy

### ISSUE THREAD

**Issue by ursbraem** [spacecatninja/craft-imager-x#178]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x ] general question

Hey!

I'm interested in using the "Blurhash thingy" in a "traditional" setup based on Twig (no Vue, GraphQL etc).
Now I found out how to get the Blurhash, via `{% set blurHash = transformedImage.getBlurhash() %}`, I'm not sure how to use it to display the actual blurred image. The websites are unspecific about it. 

https://github.com/kornrunner/php-blurhash#decoding-with-js--ts says there is a way to get a PNG. Maybe that's something already provided by imager-x? Actually, I expected a string I could add to a fallback `<img src="data:image/png;base64`. But that's apparently not how it works? Maybe I should just stick to using the dominant color for the placeholders?

**Comment by aelvan** [comment]
Hi,

The "problem" that blurhash tries to solve, is minimizing the amount of data that has to be sent from the server to the client, and still be able to create low quality image placeholders. As such, it only makes sense to use it if you do the actual decoding on the client. 

It is possible to decode the string using the PHP library that I use to create the string, but the process would be:

Image -> blurhash string -> temporary file -> base64 encoded image string -> send to client

But if a base64 encoded image is what you want, it would be easier to just use the existing functionality for creating the base64 encoded images:

Image -> base64 encoded string -> send to client

In a traditional setup with a Twig-driven frontend you can still pass the blurhash string to the client, and use the js library to decode the images. In most cases it would probably result in a worse user experience and worse performance, because you'll need to load the blurhash js library before decoding the strings, which will delay the creation of the placeholders. And it would create more work on the main thread, which is usually a critical point for performance on mobile devices.

But, I'm open for adding a helper for decoding blurhash' from PHP, if there're any arguments for it that I haven't considered. :) Let me know.

**Comment by ursbraem** [comment]
Oh, looks like I didn't really understand what it does. I was like "oh, this creates nice placeholders". But as you say, if those placeholders were rendered into a (saveable) PNG as in https://github.com/kornrunner/php-blurhash#decoding-with-js--ts – maybe in the end, they aren't so low end anymore and don't make sense as placeholders anymore?

**Comment by aelvan** [comment]
Well, for the scenario that Wolt made them, ie to be able to create image placeholders in their native apps, it made alot of sense. Because having to send the fully base64 encoded generated image, vs only the blurhash string, in the response JSON from the server to the app, makes a huge difference (without testing, I'd think we're talking 10x savings or something). And when building a headless site on Craft, where you have to boot up a full JS application on the frontend anyway, it would have the same benefits. But if you end up still transferring a base64 encoded image from the server, the whole point is gone.

**Comment by webrgp** [comment]
@aelvan I've been using the [BlurHash](https://plugins.craftcms.com/blur-hash?craft4) plugin in conjunction with Imager-X for a while now like this:

```twig
{% set blurhash = blurhashToUri(transformedImage.getBlurhash()) %}
```
And even thou I agree with everything you said, there is something to be said about having the "gradient looking blur" it generates over the other placeholders available in Imager.

In my mind it's not even about the hash itself, just how it looks. You could as well just add a new type "blurhash" to the existing [craft.imager.placeholder](https://imager-x.spacecat.ninja/templating.html#craft-imager-placeholder-config-null) function.

**Comment by aelvan** [comment]
@webrgp That is a valid point, I agree! I'll reopen and add it when I get the time.

**Comment by webrgp** [comment]
Ping me if you have a beta you need testing ;-)

**Comment by aelvan** [comment]
4.1.12 adds a `blurhash` placeholder type which can be used like this:

```
{% set transform = craft.imagerx.transformImage(asset, { width: 100 }) %}
<img src="{{ craft.imagerx.placeholder({ type: 'blurhash', hash: transform.getBlurhash(), format: 'png', width: 16, height: 9 }) }}" width="160" height="90">
```

png is the default format, and if no width and height is given it will create a 4x3px image.

**Comment by aelvan** [comment]
4.1.13 adds an additional parameter to the blurhash placeholder, `base64`, which can be set to `true` to only get the base64 encoded raw image data.

```
{{ craft.imagerx.placeholder({ type: 'blurhash', base64: true, hash: transform.getBlurhash(), format: 'png', width: 16, height: 9 }) }}
```
