### ISSUE TITLE
Blur effect is not working

### ISSUE THREAD

**Issue by veronika-g** [spacecatninja/craft-imager-x#189]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Add blur effect to image (in template or as named transform)

{% set cTestImage = craft.imager.transformImage(testImage, { effects: { grayscale: true, blur: 5 } }) %}

### Description
I added the effect blur to my images. I tried both ways (in template and as named transform). Grayscale e.g. is working well, but adding the blur effect only adds a blur that is hardly recognizable. The effect doesn't change no matter what value I choose.

### Additional info

- Imager version & edition: 4.1.7 Pro Testversion
- Imager transformer:
- Craft version:  4.2.0.2
- PHP version: 8.1.10
- Image driver & version:

**Comment by aelvan** [comment]
Hi,

Would need to know which transformer and image driver you're using. If you go to Utilities > Imager X in the control panel, you'll find that information at the bottom.

**Comment by veronika-g** [comment]
Hi!

Thanks for the quick response!

Image transformer: craft
Image Driver & Version: GD 8.1.10

Thanks!

**Comment by aelvan** [comment]
Yes, so that's the reason. As the (documentation for the blur effect says)[https://imager-x.spacecat.ninja/effects.html#blur-int-float-bool], when using GD as the image driver, blur is just a true/false thing. So no matter what number you pass in, it's just considered `true`, and you'll get the same result.

If you can enable Imagick as your (image driver)[https://craftcms.com/docs/4.x/config/general.html#imagedriver], you can send in an integer to have more levels of blur. There is also adaptiveBlur and radialBlur available, and when looking over the code I noticed that there's even an undocumented gaussianBlur. :)

**Comment by aelvan** [comment]
Sorry for the late reply, I've tested on PHP/GD 8.1.15, and the blur effect looks correct to me:

![CleanShot 2022-11-29 at 10 02 02](https://user-images.githubusercontent.com/2675644/204485248-caa6bb1a-c550-4452-a71a-cafd403d5797.png)

It might be that your version of GD for some reason doesn't support blur, but I've never encountered that so seems strange. 

Is the image shown in 1:1, or is it scaled down? The blur effect in GD is very subtle, so if the image is downsized it might be indistinguishable from the original.

Any chance you can enable Imagick and use that instead? For effects like this it offers a lot more flexibility and power than GD.
