### ISSUE TITLE
Cleanup of imager folder?

### ISSUE THREAD

**Issue by ursbraem** [spacecatninja/craft-imager-x#193]
### I'm submitting a... 

- [x ] general question

Hi! When manipulating transforms in the template, e.g. adding or removing srcset variants, and when removing images in the cp: 

Will imager remove unused rendered images from `imager` directory? Or do I kind of manually purge it? Maybe in combination with an "Auto auto auto!" action?

best
Urs

**Comment by aelvan** [comment]
Hi,

Imager will not remove any transforms that have been created due to changing transform settings. 

You can enable the `removeTransformsOnAssetFileops` config setting, to have Imager delete transforms when an asset is deleted or moved, but that's not really the scenario you're facing. 

There is a clean console command (see `./craft imager-x/clean --help`) that can delete transforms that have expired from the cache, and you can also provide a custom duration for this via the `--duration` parameter. You could maybe use this to purge any transforms that were created prior to you being finished with manipulating the transforms, but you could risk it removing more than necessary.

So yeah, don't have a perfect solution for that, but hope this helps.

**Comment by ursbraem** [comment]
Thanks!

> but you could risk it removing more than necessary.

Would the missing transforms be recreated on the fly when needed? I guess?

On the other hand, what about fully cleaning the imager-x directory on go-live of a site and rebuilding all assets from scratch? (expecting some timeouts there for the beginning)

**Comment by aelvan** [comment]
> Would the missing transforms be recreated on the fly when needed? I guess?

Yes, "removing more than necessary" maybe sounded a bit too serious. :) The transforms will be regenerated if they're missing. So I just meant that it will add a small performance hit if you remove more transforms than what was strictly necessary. 

I usually start with a clean imager directory when going to production, and then either pre-generate the transforms, or just let the site create them at runtime.

**Comment by ursbraem** [comment]
> either pre-generate the transforms

I saw this https://imager-x.spacecat.ninja/usage/generate.html#console-commands-for-generating-transforms – I haven't used named transforms on the site but made a partial that receives its parameters including aspect ratio when it's called. So to retrofit I would have to name each transform and register them globally in `imager-x-generate.php`, right?

**Comment by ursbraem** [comment]
Absolutely. Thank you very much for the help!!
