### ISSUE TITLE
Imager error

### ISSUE THREAD

**Issue by ballboubou1** [spacecatninja/craft-imager-x#195]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [ * ] general question

### Steps to reproduce

1. ...
2. ...
3. ...

### Description
 

Hello, I just upgraded from craft 3 to 4 and I have errors with imager, can someone please help me
### Displayed errors, stack trace, relevant logs  

spacecatninja\imagerx\variables\ImagerVariable::transformImage(): Argument #1 ($file) must be of type craft\elements\Asset|spacecatninja\imagerx\adapters\ImagerAdapterInterface|string, null given, called in C:\wamp64\www\craft\vendor\twig\twig\src\Extension\CoreExtension.php on line 1607
```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

  {% elseif entry.imageFormat.value == "landscape" %}
            {% set image = entry.image.one ?? null %}
            {% set transformedImage = craft.imager.transformImage(image, {
            width: 1640,
            height: 1100,
            effects: { grayscale: true },
            }) %}
        {% endif %}

### Additional info

- Imager version & edition: 4.1.9.1
- Imager transformer:
- Craft version: 4
- PHP version: 8
- Image driver & version:

**Comment by aelvan** [comment]
Hi, 

The underlying issue here is that you pass in `null` as an image. This currently generates an error, because of strong typing in version 4.x, whereas it would just be ignored in 3.x (`transformImage` will return `null`, though). Although the better solution is to code defensively and for instance wrap the code that calls `transformImage` in an `{% if image %}`, I'll loosen the typing on `ImagerVariable::transformImage()` to accept `null` in the nest release to make things a bit easier. I'll let you know when it's out.

**Comment by ballboubou1** [comment]
Thanks, it's work

**Comment by aelvan** [comment]
This was amended in 4.1.10.
