### ISSUE TITLE
Rounding issue on srset images and odd duplication of last two images

### ISSUE THREAD

**Issue by terryupton** [spacecatninja/craft-imager-x#201]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
So this isn't a consistent issue and is only happening on some images, but this is also across different transform presets.
I have several different instances of this. 

The original image source width is 1050×786.
So it is odd why it is stopping at 866px and 867px.
I would expect a 900px and 1000px images instead.

<img src="https://cdn.discordapp.com/attachments/575387375610626063/1080088426562465803/Screenshot_2023-02-28_at_11.24.16.png" />
<img src="https://cdn.discordapp.com/attachments/575387375610626063/1080088426889625630/Screenshot_2023-02-28_at_11.24.10.png" />

### Description
The transforms are done using  named transforms. 
The one form the example above looks like this:
```php
'Teaser'               => [
    'displayName' => 'Teaser Image',
    'transforms'  => [
      ['width' => 400],
      ['width' => 1200],
    ],
    'defaults'    => [
      'ratio' => 8 / 7.25,
      'auto'  => static function ($image) {
        if ($image instanceof \craft\elements\Asset) {
          if ($image->getFieldValue('autoEnhanceImage') === false) {
            return 'compress,format';
          }
        }
        return 'compress,format,enhance';
      }
    ],
  ],
  ```
  
  ```twig
{% set transformedImages =  craft.imagerx.transformImage(image, 'Teaser') %}
    
<picture class="{{ classPicture }}">
  <img
    src="{{ placeholder }}"
    srcset="{{ transformedImages | srcset }}"
    sizes="{{ vars.sizes }}"
    width="{{ imageWidth }}"
    height="{{ imageHeight }}"
    alt="{{ vars.alt }}"
    class="{{ classImage }}"
    {% if vars.objectFit %}style="{{ styleImage }}"{% endif %}
    {% if vars.lazy == true %}loading="lazy"{% endif %}
  >
</picture>
  ``` 
  
 
### imager-x.php settings file
```php
return array(
  '*'     => [

    'fallbackImage'    => '/assets/img/fallback.jpg',

    // ------------------------------------------------------------
    // Environment: ALL
    // ------------------------------------------------------------
    'transformer'      => App::env('IMAGER_TRANSFORMER') ?: 'craft',
    'imagerSystemPath' => '@webroot/transforms/',
    'imagerUrl'        => '@siteUrl/transforms/',


    'cacheEnabled'             => true,
    'cacheDuration'            => 31536000, // 1 year
    'cacheDurationRemoteFiles' => 31536000, // 1 year

    'jpegQuality'                    => 80,
    'allowUpscale'                   => false,
    'removeMetadata'                 => true,
    'resizeFilter'                   => 'triangle',
    'interlace'                      => 'line',
    'removeTransformsOnAssetFileops' => 'true',

    //As we are uisng Imgix this creates lots of transforms which is great for responsive images and performance.
    'fillTransforms'                 => true,
    'fillInterval'                   => 100,

    'imgixApiKey'  => App::env('IMGIX_API_KEY'),
    'imgixProfile' => App::env('IMGIX_PROFILE'),

    'imgixConfig' => [
      'staging' => [
        'domain'                     => 'Removed for this post',
        'useHttps'                   => true,
        'signKey'                    => App::env('IMGIX_SIGN_KEY'),
        'sourceIsWebProxy'           => false,
        'useCloudSourcePath'         => true,
        'getExternalImageDimensions' => true,
        'defaultParams'              => [
          'auto' => 'compress,format,enhance', 'q' => 80
        ],
        'addPath'                    => [
          'images'   => 'images',
          'projects' => 'projects',
          'staff'    => 'staff',
        ],
      ],
    ],


    'optimizers'      => ['mozjpeg', 'pngquant', 'optipng'],
    'optimizerConfig' => [
      'mozjpeg'  => [
        'extensions'   => ['jpg'],
        'path'         => '/usr/bin/mozjpeg',
        'optionString' => '-optimize -copy none',
      ],
      'optipng'  => [
        'extensions'   => ['png'],
        'path'         => '/usr/bin/optipng',
        'optionString' => '-o2 -strip all',
      ],
      'pngquant' => [
        'extensions'   => ['png'],
        'path'         => '/usr/bin/pngquant',
        'optionString' => '--strip --skip-if-larger',
      ],
    ]
  ],
```

### Additional info

- Imager version & edition: 4.1.10 (pro)
- Imager transformer: Imgix
- Craft version: Craft Pro 4.3.10
- PHP version: 8.0.20
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.0-39)

**Comment by aelvan** [comment]
I've fixed the rounding error that resulted in non-integer values being passed to Imgix for width/height, so you should no longer see that error. 

> So it is odd why it is stopping at 866px and 867px.
> I would expect a 900px and 1000px images instead.

If `allowUpscale` is set to `false`, Imager will check both width and height to see if the image will be upscaled. In this case, 786px is the largest height possible, alas the transforms above that point will have that height, and the corresponding width for your given ratio.

The fact that there's one at 866px and 867px, is due to a caveat with `allowUpscale`, that I haven't found a good solution to which doesn't sacrifice performance. Imager will always create transforms for all the transforms in the array you pass in, even the once that have been limited by `allowUpscale`. So there will actually be created transforms for widths 900, 1000, 1100 and 1200 too, as shown in this excerpt from the transforms I created as a test:

![CleanShot 2023-03-05 at 21 41 49](https://user-images.githubusercontent.com/2675644/222984813-8d15da3c-414f-4da7-91d0-99040135bb33.png)

For each of these, Imager will take the original width and height, and constrain them by the actual size of the image. Which results in slightly different values for the width.  Now, when you pass them through `srcset`, any duplicate widths will be filtered out, so that in practice it won't affect the users experience. But, hence, the side effect where you get one image that's 867px wide, and one that's 868px, for this particular combination of circumstances.
