### ISSUE TITLE
Clear Imager transforms automatically when deleting an asset.

### ISSUE THREAD

**Issue by alexroper** [spacecatninja/craft-imager-x#21]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
 

When deleting an asset from the control panel, it would be helpful if Imager deleted the transformed images for that asset as well. Currently admins can run "Clear Imager transforms" before they delete an image, but it would be helpful if this happened automatically.

### Additional info

- Imager version & edition: 3.0.7 Pro
- Imager transformer: craft
- Craft version: 3.3.19
- PHP version: 7.3.8
- Image driver & version: Imagick 3.4.3
- Database driver & version: MySQL 5.7.26
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Myeah, this has come up from time to time. I'm not a huge fan. :)

Can I ask what your main motivation for having this functionality would be?

**Comment by alexroper** [comment]
The reason is simply less space taken up on the server. I can't think of a reason why anyone would need image transforms for images that don't exist anymore.

The only way to clean up unused image transforms is to delete ALL image transforms and remake them from scratch.

Alternately, some sort of garbage collection routine could help with this. Something that could run to remove image transforms if the asset no longer existed.

**Comment by aelvan** [comment]
Forgot to reply to this one... One reason to keep image transforms would be to be able to serve images that appear in cached content. If you run some kind of front-side cache, the cache will probably not be invalidated as instantly as the image and transforms are deleted. Resulting in broken images for users who get served the cached html. Another one is images that have been shared on other platforms.

One could argue that if you delete an image, it's a purposeful action to actually remove the image from the internet. But if the goal of this FR is to save disk space, image transforms would also need to be invalidated when an image is _moved_, since the image no longer will have the same transform path. So someone could end up inadvertently breaking cached content just by tidying up their assets.

That said, only deleting transforms on delete would help somewhat, so maybe it's a _good enough_ solution.

I'm also pondering making a new console command that goes through the imager system path and checks if there are outdated transforms and deletes them. That would probably be thebest solution to save disk space, and it could be run as part of a monthly maintenance or something. Not 100% sure if it's doable yet, but I'll give it a go when I find the time.

**Comment by aelvan** [comment]
I added functionality for automatically deleting transforms on asset delete/move to v3.1.0.

This is turned off by default, you enable by setting `removeTransformsOnAssetFileops` to `true` in the config. See 
[the documentation](https://imager-x.spacecat.ninja/configuration.html#removetransformsonassetfileops-bool) for
notes and warnings. ;)

I'll continue pursuing the console command clean/sync route, but for some use-cases this is probably a good approach.

**Comment by alexroper** [comment]
I love it. Thank you very much!

The console command sounds like an excellent idea. Especially for existing sites with years of built up image transforms that might need to be cleaned up.

The scenario I imagine this helping with is where admins are uploading and trying out different images. They might delete them, move them around, or leave old versions in asset volumes that they later realize they don't need and delete. Possibly before content is ever published.
