### ISSUE TITLE
Generate Placeholders

### ISSUE THREAD

**Issue by webrgp** [spacecatninja/craft-imager-x#220]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
Hi André! I've using your plugin in a lot of sites, specially after you added the Blurhash placeholder. I lean heavily on named transforms and automatic generation, but when loading the page for the first time (like articles listing pages), it takes a bit to load because it's generating the placeholder at the template level.

I was wondering if there is a way to generate those with the named transform configuration, so they get generated with it.

Thanks again!

**Comment by webrgp** [comment]
I guess adding a `placeholder` option on the `transformDefaults` would be the most logical place: it can be used both in template and in named transforms.

Because the Blurhash require access to the asset, that's where it makes more sense to me.

Maybe there is an opportunity to just set the default placeholder strategy in the `imager-x`.

Now that I am actually reading what I just wrote, I think it makes a lot of sense to move the placeholder config into `imager-x`: it could be use to generate on transform, either at the template level or at the config.

I mainly use the Blurhash placeholder in my projects since you made it available and all my clients love it. I am even updating older projects with it and I maintain them. The single drawback is that I can't pre-generate it.

**Comment by aelvan** [comment]
Myeah, I'm leaning more towards adding this to a new property on named transforms, that can be used to generate (or rather, cache) various types of additional things on generate. Like, blurhash, dominant color, palette, etc.

But could you supply an example of how you use blurhash as a placeholder, so I'm sure we're talking about the same scenario. Because there's actually two different issues here, just want to make sure we're talking about the same thing.

**Comment by webrgp** [comment]
Sure! I have a `_img/twig` template that I use on most projects with minor modifications:

```twig
{#

Image / Picture Component

Usage:
{{ include('_components/_img', { Parameters }) }}

Parameters:
- imgAsset: Asset (required). The Asset source from Craft CMS
- classes: Array (optional). An array of classes to be applied to the <img> tag
- pictureClasses: Array (optional). An array of classes to be applied to the <picture> tag
- sizes: String (optional). The sizes attribute for the <img> and <source> tags
- loading: String (optional). The loading attribute for the <img> tag. Defaults to 'lazy'
- transform: String | Array (optional):

  The transform(s) to be applied to the image. If the transform is a string,
  it will use the named transform in the `imager-x-transforms.php` config file.

  If the transform is an array, it will use the array as the transform
  configuration. See https://imager-x.spacecat.ninja/transform-parameters.html
  for more info.
#}

{# prettier-ignore-start #}
{% set allowedTags = ['img', 'picture'] %}

{% if imgAsset is defined and imgAsset %}

  {####### Defaults #######}
  {# <img> default classes #}
  {% set imgDefaultClasses = [] %}

  {% set defaultTransform = [
    { width: 1024 },
    { width: 768 },
  ] %}

  {####### Utilities and Checks #######}
  {% set isGif = imgAsset.extension == 'gif' %}
  {% set isSVG = imgAsset.extension == 'svg' %}

  {####### <img> Attributes #######}
  {% set alt = imgAsset.alt|default(imgAsset.title) %}
  {% set sizes = sizes|default('100vw') %}
  {% set imgClasses = [] %}

  {% if classes is defined and classes %}
    {% if classes is not iterable %}
      {% set classes = [classes] %}
    {% endif %}

    {% set imgClasses = imgDefaultClasses|merge(classes) %}
  {% else %}
    {% set imgClasses = imgDefaultClasses %}
  {% endif %}

  {# <img> Base Config  #}
  {% set baseImgConfig = {
    sizes: sizes,
    class: imgClasses,
    alt: alt,
    loading: loading|default('lazy'),
  } %}

  {% if isSVG %}
    {# Inline as <svg> if asset has .svg extension #}
    {% set svgOutput = svg(imgAsset) %}
    {{ svgOutput|retcon('attr', 'svg', { 'class': imgClasses })|raw }}
  {% else %}

    {# Get focal point position from asset #}
    {% set position = [
        imgAsset.focalPoint.x * 100,
        imgAsset.focalPoint.y * 100,
      ]|map( v => v ~ '%' )|join(' ')
    %}

    {# Transforms #}
    {% set transformedImages = craft.imagerx.transformImage(
      imgAsset,
      transform|default(defaultTransform),
      { position: position }
    ) %}

    {% if transformedImages|length %}

      {% set firstTransformed = transformedImages|first %}
      {% set lastTransformed = transformedImages|last %}
      {% set aspectRatio = lastTransformed.height / lastTransformed.width %}

      {% set blurhash = craft.imagerx.placeholder({
        type: 'blurhash',
        hash: lastTransformed.getBlurhash(),
        format: 'png',
        width: 8,
        height: (8 * aspectRatio)|round,
      }) %}

      {% set imgConfig = baseImgConfig|merge({
        src: lastTransformed.url,
        srcset: transformedImages|srcset,
        width: lastTransformed.width,
        height: lastTransformed.height,
        style: "aspect-ratio: #{lastTransformed.width} / #{lastTransformed.height};background-image: url('#{blurhash}'); background-repeat: no-repeat; background-size: cover;",
      }) %}

      {% tag 'picture' with {
        class: pictureClasses|default([]),
      } %}
        {% if craft.imagerx.clientSupports('webp') and not isGif %}
          {# Webp Transforms #}
          {% if transform is string %}
            {% set transformedWebps = craft.imager.transformImage(
              firstTransformed,
              transform ~ 'Webp',
            ) %}
          {% else %}
            {% set transformedWebps = craft.imagerx.transformImage(
              firstTransformed,
              transform|default(defaultTransform),
              { format: 'webp', position: position }
            ) %}
          {% endif %}
          {{ tag('source',{
            srcset: transformedWebps|srcset,
            sizes: sizes,
            type: 'image/webp',
          })}}
        {% endif %}
        {{ tag('img', imgConfig) }}
      {% endtag %}
    {% endif %}
  {% endif %}
{% endif %}
{# prettier-ignore-end #}

```

**Comment by aelvan** [comment]
Thank you! 

The thing taking time here isn't actually the creation of the placeholder, but `lastTransformed.getBlurhash()`. So I think the approach I was thinking of to this can help. 

But, curious, in what order do you typically pass in your transforms, smallest to largest or largest to smallest? Ie, will `lastTransformed` usually be the biggest or the smallest transform? The blurhash algorithm loops though every pixel in the image, so it's a good idea to only use it on small images.

**Comment by webrgp** [comment]
Yes, but keep in mind that the reason I am creating the placeholder on the last transform is because it's the smallest file and because of that, I assumed that the placeholder creating would go faster.

**Comment by aelvan** [comment]
Imager X 4.2.0 is out with some things that address this issue. 

Named transforms now have a new setting, `generateFlags`, that can be used to warm the cache for blurhash, dominant color and color palette for the transformed images. Example:

```
    'myTransforms' => [
        'displayName' => 'My transforms',
        'transforms' => [
            ['width' => 600],
            ['width' => 1500],
        ],
        'defaults' => [
            'ratio' => 16 / 9
        ],
        'configOverrides' => [
            'fillTransforms' => true,
            'fillInterval' => 300,
        ],
        'generateFlags' => ['blurhash', 'palette', 'dominantColor']
    ],
```

It's important to note that this will only run the relevant methods on the transformed image to generate and cache the results. Imager currently doesn't have anywhere to store this information in a persistent way, so emptying the data cache will remove this information. I'm working on a separate cache for Imager that will improve this, but that will be for a later version. 

In addition to this, I've changed the way pixels are sampled when creating the blurhash. Previously, all pixels would be extracted from the source image and passed to the blurhash method, which was really excessive since the algorithm in the end only spits out about twelve pixels that goes into the blurhash string. After 4.2.0, a maximum of 100 pixels horizontally (spaced out over the total width of the image) will be extracted, making the resource usage a lot less, and more predictable.

Although this doesn't actually address the generating of placeholders, it should resolve the base issue, because what takes time here is not the actual creation of the placeholder, but extracting the blurhash string. It's not perfect due to the caching being used, but that's a separate issue that needs to be addressed at some point. 

Will close for now.

**Comment by webrgp** [comment]
Great!

Let me ask a separate question: I see that in your sample code your transforms go from small to large. Is that your recommendation?

**Comment by aelvan** [comment]
No, that's just my personal preference. I think at some point I thought that `srcset` worked the same way as `sizes` and `<source>` inside `<picture>`, in that it picked the first "match" from the list of candidates. Ie, if the biggest image was first, it would always pick that. But I'm 99% sure that I had this "huh"-moment before and testet it, and it doesn't work that way... So, just my preference. ;)
