### ISSUE TITLE
cURL error “60” encountered while attempting to download using MAMP Pro host with SSL enabled

### ISSUE THREAD

**Issue by romainpoirier** [spacecatninja/craft-imager-x#221]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. Setup a MAMP Pro host with SSL enabled
2. Distribute image file over secured URLs from a custom controller
3. Try to display image using `craft.imagerx.transformImage()`
4. Get the SSL error

### Description
 
I get an error while trying to display a transform image from a specific URL that returns an image securely distributed.

```
{% set transformedUrl = '{base}/actions/secret/file/view?entryId={entryId}&attachmentId={attachmentId}' | t({
	base: alias('@web'),
	entryId: entry.idNumber,
	attachmentId: attachmentId
}) %}
{% set transformedImage = craft.imagerx.transformImage(transformedUrl, {
	width: 800
}) %}
{{ tag('img', {
	src: transformedImage.url,
	alt: true
}) }}
```

### Displayed errors, stack trace, relevant logs  

```
Exception – spacecatninja\imagerx\exceptions\ImagerException
cURL error “60” encountered while attempting to download “https://website.local/actions/secret/file/view?entryId=424&attachmentId=93”. The error was: “SSL certificate problem: unable to get local issuer certificate”
```

While direct access to the URL `https://website.local/actions/secret/file/view?entryId=424&attachmentId=93` in the browser is returning the image.

For information, the image is queried using `accept: application/octet-stream` in the `header` (API requirement), and using the `file_get_contents()` PHP function to return it.

This is a local URL, and the certificate is valid as shown in Google Chrome without any warning and a current validity.

### Additional info

- Imager version & edition: 4.1.13
- Imager transformer: Craft
- Craft version: 4.4.15
- PHP version: 8.0.20
- Image driver & version: Imagick 3.5.1 (ImageMagick 6.9.6-2)

**Comment by aelvan** [comment]
Hi,

The issue is that PHP/curl has not been configured correctly and/or that the certificate provided (on PHP's end, not the site you're accessing) has issues. See this thread for pointers and possible solutions:

https://stackoverflow.com/questions/67228537/mamp-local-development-curl-error-60-ssl-certificate-unable-to-get-local-iss

**Comment by romainpoirier** [comment]
Yes I've already checked StackEchange before, and tried the solution of downloading the PEM and setting the path in the php.ini of the PHP version I'm using. Sorry for not having mentioning that. But unfortunately, it doesn't work for me, and I still get the error. By any chance, do you have any other suggestion?

**Comment by romainpoirier** [comment]
I also tried to disable the SSL in my local env using `verify_peer` and `verify_peer_name` set to `false` when querying my image file using cURL, but I still get the error. Is there any option to disable this verification in `devMode` (local test only purpose) at the level of the Imager plugin?

**Comment by aelvan** [comment]
If you need to change the curl configuration that Imager uses, you can use the [`curlOptions` config setting](https://imager-x.spacecat.ninja/configuration.html#curloptions-array).

**Comment by romainpoirier** [comment]
Thank you very much, it works.

I've got one more challenge: my asset URL is secured, to check the permission before being authorized to open the image.

Currently, the controller that is returning the image is checking that the user is logged in and has the right permissions. First with `protected array|int|bool $allowAnonymous = self::ALLOW_ANONYMOUS_NEVER;` on top of the file, next inside the controller function.

I understand that here the cURL query is made from the Imager X plugin: how can I tell my controller to always allow request from the plugin? How can I identify them? Could it also work combined with `$allowAnonymous`?

**Comment by aelvan** [comment]
What happens currently? Do the curl request to the controller fail?

**Comment by romainpoirier** [comment]
For no reason, I can't replicate the error right now. I will update later if I find again what was blocking.

The only clue I found was to add this within my controller, before to check for an active user session:
> if (strpos($_SERVER['HTTP_USER_AGENT'], 'curl') == false) {

But it's still useless as it's not secured at all, and doesn't filter if the request is coming from the Imager X plugin.

Do you have any tips to secure the request from my controller to be able to accept anonym request only if there's targetting an action to the Imager X plugin?

**Comment by aelvan** [comment]
It's difficult to know exactly what the best solution would be, without knowing more about what your use-case is. But, based on what I can gleam, I think I would recommend against using a controller at all.

If the case is that you have some protected page on your site that needs to show transformed versions of some protected images, I would rather create a template variable or twig function, pass the necessary information to it, and do the transforms with [Imager in PHP](https://imager-x.spacecat.ninja/usage/php.html). This has two main benefits; 1) you retain the normal, built-in Craft security throughout the whole operation, and 2) if you're transforming an actual Asset, Imager will benefit from knowing this in terms of cache breaking (ie, when using the controller approach, it will interpret this as an external URL, and no cache breaking will occur). 

But again, I have no idea what the actual use-case here is, so it may not be feasible. 

If you want to continue the controller route, there're a couple of approaches you could use to secure it. One is setting the HTTP_USER_AGENT you mentioned to something unique, using CURLOPT_USERAGENT in the curlOptions config setting. It's a bit of security through obscurity though.

The better solution is probably to create some kind of unique access token per transform, that is based on the known data, and something secret. Something like:

```
{% set transformedUrl = '{base}/actions/secret/file/view?entryId={entryId}&attachmentId={attachmentId}&accessToken={accessToken}' | t({
	base: alias('@web'),
	entryId: entry.idNumber,
	attachmentId: attachmentId,
         accessToken: myHashFunction(entry.slug ~ '_' ~ attachmentId ~ '_' ~ myVerySecretToken) 
}) %}
```

And then validate that inside your controller. As long as the token is secret, and the hashing is reasonably hard, that would be a secure approach.

Make sure the accessToken isn't too unique though, since Imager will create new image transforms per change.

**Comment by aelvan** [comment]
@romainpoirier Did you figure out a solution?

**Comment by romainpoirier** [comment]
I'm so sorry for the late reply. I really appreciate you took the time to suggest a clever solution.

I've now implemented your `accessToken` suggestion, and as far as I have secured it now (still need improvement on my side), it works.

Also, this new param combined to `'cacheRemoteFiles' => false` + `'cacheDurationRemoteFiles' => 0` fix my caching issue where the image link wasn't updated. I don't know why, but it looks like before that it wasn't updating the transform, even if the source URL was changing.

However, I'm maybe considering using another library like [Intervention](https://image.intervention.io/v2/api/make) that allows to provide a binary image data as source. In my case, that's how my secured URL are delivered (as data, not as URL), so it looks like a cleaner logic within my controller. Do you think this would be possible also with Imager in PHP?

**Comment by aelvan** [comment]
> Also, this new param combined to 'cacheRemoteFiles' => false + 'cacheDurationRemoteFiles' => 0 fix my caching issue where the image link wasn't updated. I don't know why, but it looks like before that it wasn't updating the transform, even if the source URL was changing.

This sounds a bit strange. Maybe you hadn't set `useRemoteUrlQueryString` to `true`? Although, in that case you probably wouldn't get anything back at all.. 🤔

The underlying library that Imager and Craft use, Imagine, doesn't support loading binary data directly, so that's unfortunately not possible.

**Comment by romainpoirier** [comment]
Thank you. You're right, `useRemoteUrlQueryString` wasn't setup, as it's not enabled by default.
But as you said, that would be strange as I had already the `entryId` & `attachmentId` params.
I'll keep you updated if I get more details about that.
