### ISSUE TITLE
runJobsImmediatelyOnAjaxRequests by default overrides the Craft general setting for runQueueAutomatically

### ISSUE THREAD

**Issue by JoshCoady** [spacecatninja/craft-imager-x#224]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Steps to reproduce

1. config Craft [runQueueAutomatically](https://craftcms.com/docs/4.x/config/general.html#runqueueautomatically) to false
2. include Image X plugin with default config

### Description
 

It was unexpected that the default behavior of Imager X would be to run the job queue automatically on the web server when Craft was configured to not run the job queue automatically at all.

Now that we know this is how Imager X behaves, we can disable the setting to get Imager X to behave the way we want it to, but the default behavior was unintuitive.

Expected behavior:

A. `queue/run` is only triggered by Imager X if both `runJobsImmediatelyOnAjaxRequests` AND `runQueueAutomatically` are set to true. 

-OR-

B. When `runQueueAutomatically` is set to false, `queue/run` is only triggered by Imager X if `runJobsImmediatelyOnAjaxRequests` is manually configured to true (not based on a default setting).

### Additional info

- Imager version & edition: 4.1.13 pro
- Imager transformer:
- Craft version: 4.4.14
- PHP version: 8.1.20
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.1-10)

**Comment by aelvan** [comment]
Hi, thanks for reporting. I agree, it should work like described in option A, this has been changed for the next release. 

I don't think `runQueueAutomatically` was a thing back when I implemented the hacky `runJobsImmediatelyOnAjaxRequests` behaviour for Craft 2. In fact, in a future release it should probably be deprecated and removed, since using a dedicated queue runner is a much better option for Craft these days.
