### ISSUE TITLE
how to optimize images via jpegoptim, TinyPNG or else?

### ISSUE THREAD

**Issue by ballmannweber** [spacecatninja/craft-imager-x#26]
I can't find anything about optimizing images via tinypng or jpegoptim in the documentation despite this is such a big feature teased in the plugin's product description. and if I search for "optimizer" I find an empty optimizers-page: https://imager-x.spacecat.ninja/usage/optimizers.html

since I heard so much positive stuff about imager (x) I thought this is a bit rough?

**Comment by aelvan** [comment]
You're right, there should be a help page about optimizers. The one you found was where it was suppose to be, but I never got around to writing it. I'll put it back on my list (near the top).

For now, the important information is that the relevant config settings is `optimizers`, `optimizeConfig` and `optimizeType`, see:

https://imager-x.spacecat.ninja/configuration.html#optimizers-array
https://imager-x.spacecat.ninja/configuration.html#optimizerconfig-array
https://imager-x.spacecat.ninja/configuration.html#optimizetype-string

Let me know if you have any concrete questions that I might help answer.

**Comment by ballmannweber** [comment]
Thank you very much for your quick answer!

I am still very new to Craft and have just ported our very image-heavy website from ExpressionEngine to Craft. One of the things that bothered me about EE for a long time was that there were no plugins available to automatically compress images (like TinyPng for example). Therefore, at the moment I want to use Imager mainly to compress/optimize the hundreds of images we use on the site for all 20 created transformations (jpegoptim, tinypng, etc.). 

Since we use many image grids in the frontend, which we can select individually in the backend via a pulldown menu, we have a code that contains many conditionals and queries. 

Maybe you could show me an example of how I can apply Imager's image optimizations to this code? Here is a short excerpt of the code:

```
{% for entry in craft.entries.section('projects').with(['start screens']).all() %}

{% macro responsiveImg(asset, transformHandle) %}
<img src="{{{ asset.getUrl(transformHandle) }}" 
	srcset="{{ asset.getUrl(transformHandle) }} 1x, 
			{{{ asset.getUrl(transformHandle ~ '2x') }} 2x" 
	width="{{{ asset.width(transformHandle) }}" 
	height="{{{ asset.height(transformHandle) }}" 
	alt="{{ asset.title }}">
{% endmacro %}

	<figure class="grid {{{ entry.orderlayoutlayout }}">	
	{% elseif entry.arrangementStarting pictures == "q1q2" %}
	{% for image in entry.start images %}
		{% if loop.index == 1%}
		{% if image.kind == 'image' %}
		<figure class="q1">
			{{ _self.responsiveImg(image, 'eins2quer') }}
		</figure>
	{% else %}
			<video class="q1" autoplay loop muted playsinline>
			<source src="{{{ image.getUrl() }}" type="video/mp4">
		</video>
	{% endif %}
	{% elseif loop.index == 2 %}
		{% if image.kind == 'image' %}
			<figure class="q2">
				{{ _self.responsiveImg(image, 'eins2quer') }}
			</figure>
		{% else %}
				<video class="q2" autoplay loop muted playsinline>
				<source src="{{{ image.getUrl() }}" type="video/mp4">
			</video>
		{% endif %}
	{% endif %}
{% endfor %}
```

Since image files as small as possible are very important for our website, we would also use the PRO version of Imager, since I have seen that it creates transformations automatically during upload. 

And we've looked at several plugins for Craft, but since Imager(X) has been around for a long time and the plugin looks very mature to us, we think it would actually be the best choice for this application. 

Therefore I was probably surprised that the chapter on optimizations is empty :-)

**Comment by ballmannweber** [comment]
hi @aelvan, any thoughts about my question?

**Comment by aelvan** [comment]
Yeah, let me try to give you some pointers. Exactly how to configure things and how to use Imager, largely depends on your environment, project, personal preferences and trade-offs between resources and results – but here's my take.

First, you'll have to configure which optimizers to use. For the purpose of this example, let's use `jpegoptim` for jpegs, `tinypng` for pngs, and `gifsicle` for gifs. `jpegoptim` and `gifsicle` are command line tools that you install on your local machine/server. How, depends on your environment. On an ubuntu server you'd do `sudo apt-get install jpegoptim` and `sudo apt-get install gifsicle`. On OSX with brew installed, you'd do `brew install jpegoptim` and `brew install gifsicle`. You can test if they're already installed, or if the installation was successful by running `jpegoptim` and `gifsicle` from your command line. If you're uncertain where they're stored, use `which jpegoptim` to get the path.

To use TinyPNG, you need to make an account and get an API key from https://tinypng.com/. Please note that TinyPNG can also be used to optimize jpegs, but in this example I only use it for pngs (that's what the `extensions` setting per optimizer is for).

With those installed, add the following to your `imager-x.php` config file: 

```
'optimizeType' => 'job',
'optimizers' => ['jpegoptim', 'gifsicle', 'tinypng'],
'optimizerConfig' => [
    'jpegoptim' => [
        'extensions' => ['jpg'],
        'path' => '/usr/local/bin/jpegoptim',
        'optionString' => '-s --all-progressive',
    ],
    'gifsicle' => [
        'extensions' => ['gif'],
        'path' => '/usr/local/bin/gifsicle',
        'optionString' => '--optimize=3 --colors 128',
    ],
    'tinypng' => [
        'extensions' => ['png'],
        'apiKey' => 'YOUR-API-KEY-HERE',
    ],
],
```

_This is just an example_. Make sure the path's correspond to where `jpegoptim` and `gifsicle` is in your environment. The options should be changed to your preferences. In the example above, all jpegs are made progressive, and gifs are reduced to 128 colors. That may not necessarily be to your liking.

The config setting `optimizeType` indicates whether Imager should optimize the files when the transform is made (`'runtime'`), or as a separate queue job after the request has finished (`'job'`). It's usually best to do it as a queue job, but make sure you understand how the Craft queue work, and preferably use a queue runner to make sure the queue runs continuously (see https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms). If you do optimizations via a queue job, the image will first be transformed and made available to the request, and then be replaced when your job runs. This means you can see unoptimized files on disk, and end-users may get served unoptimized files (but with a short cache duration), in the interim.

With that set up, _any transforms you do with Imager will automatically use the optimizers_.

Currently you're using Craft's native image transforms in your example code. The absolutely simplest way to make transforms with Imager instead, is to enabled the [`useForNativeTransforms`](https://imager-x.spacecat.ninja/configuration.html#usefornativetransforms-bool) config setting. With that enabled you wouldn't have to do any changes to your code. Unfortunately, it comes with the major drawback of not being able to use [the generate functionality](https://imager-x.spacecat.ninja/usage/generate.html), since the transforms you're referencing are Craft's native ones, not Imager's [named transforms](https://imager-x.spacecat.ninja/usage/named-transforms.html). You _could_ recreate those as named transforms too, but it's a bit fragile and error prone.

So, I'd recommend rewriting your code to use Imager's templating syntax, [you can read more about it here](https://imager-x.spacecat.ninja/usage/). In short, `{{ asset.getUrl(transformHandle) }}` is replaced by `{{ craft.imager.transformImage(asset, namedTransformHandle).getUrl() }}`. But, make sure to always code defensively, so something like this is better:

```
{% set transformedImage =  craft.imager.transformImage(asset, namedTransformHandle) %}

{% if transformedImage %}
    {# ...do your thing... #}
{% endif %}

{# ...or... #}

{{ craft.imager.transformImage(asset, namedTransformHandle).getUrl() ?? '' }}
```

Now... How to use this in your example is a question not easily answered. Firstly, it seems like your images are not actually responsive, since you set the width and height properties of your img tag. Also, you're getting the width and height from the transforms, which is kind of a round-about way of doing things that doesn't really have an equivalent with Imager's named transforms. And lastly, you're using a srcset with 1x and 2x, which really is a relic of the past and to be considered an anti-pattern these days.  

I can't really delve deep into this, but I'd recommend; 1) let your css decide the size of your images, and 2) use srcset and sizes to let the browser choose the best image for the job. For a good explanation of srcset and sizes, I still find [this article from 2014](https://ericportis.com/posts/2014/srcset-sizes/) to be the best starting point. With that approach you'll deliver a much more optimized experience to your end users, and will benefit even more from Imager's syntax and tools.

Good luck!

**Comment by ballmannweber** [comment]
hi @aelvan, thank you very much for your lenghty and detailed reply! I've red the linked articles and find the last one about scrset und sizes really helpful because I wasn't happy at all with the 1x/2x-srcset. I have to rebuild the code to see if I understood the article correctly (language barrier, I am german :-).

now, about imager. since I want to consider using imager right from the beginning with the new code… if you look at my example code and strip the 1x/2x and the width/height in the code… how would I need to change the code to get any imager output at all?

I´ve red the imager docs and managed to use that example code on another part of the website. but with this…

```
{% for entry in craft.entries.section('projects').with(['start screens']).all() %}

{% macro responsiveImg(asset, transformHandle) %}
<img src="{{{ asset.getUrl(transformHandle) }}" alt="{{ asset.title }}">
{% endmacro %}

	<figure class="grid {{{ entry.orderlayoutlayout }}">	
	{% elseif entry.arrangementStarting pictures == "q1q2" %}
	{% for image in entry.start images %}
		{% if loop.index == 1%}
		{% if image.kind == 'image' %}
		<figure class="q1">
			{{ _self.responsiveImg(image, 'eins2quer') }}
		</figure>
	{% else %}
			<video class="q1" autoplay loop muted playsinline>
			<source src="{{{ image.getUrl() }}" type="video/mp4">
		</video>
	{% endif %}
	{% elseif loop.index == 2 %}
		{% if image.kind == 'image' %}
			<figure class="q2">
				{{ _self.responsiveImg(image, 'eins2quer') }}
			</figure>
		{% else %}
				<video class="q2" autoplay loop muted playsinline>
				<source src="{{{ image.getUrl() }}" type="video/mp4">
			</video>
		{% endif %}
	{% endif %}
{% endfor %}
```

I cannot get ANY imager output – I don't understand, where to put which imager tags. that is my main problem at the moment.

**Comment by aelvan** [comment]
In your example, changing the macro to this would be the equivalent with Imager:

```
{% macro responsiveImg(asset, transformHandle) %}
<img src="{{ craft.imager.transformImage(asset, transformHandle).getUrl() }}" alt="{{ asset.title }}">
{% endmacro %}
```

_IF_ you create named transforms in Imager that corresponds with your `transformHandle`. As I said above, Imager can't use the transforms that you create in the Craft control panel, it has it's own system for that.

**Comment by aelvan** [comment]
There is now an updated page about optimizers in the docs: https://imager-x.spacecat.ninja/usage/optimizers.html
