### ISSUE TITLE
Aws cloudfront distribution has been incurring high costs  after using imager-x plugin 

### ISSUE THREAD

**Issue by Brijeshgrg1999** [spacecatninja/craft-imager-x#262]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [ X  ] general question

### Description
 
Hi , I have been using CDN and amazon s3 for my assets management for my website for a while but since I updated my website with imager-x plugin , I have been noticing high cost spike usage for cloudflare . Before using imager x I never had this kind of spike noticed ever , Can you help me to understand what might be the reason for this one ?  or is there anything wrong with my config for imager x ? 

### Additional info

- Imager version & edition: 4.4.0
- Craft version: craft pro 4.8.9
- PHP version: 8.3.6
- Image driver & version: GD 8.3.6

**Comment by aelvan** [comment]
Hi,

My guess is that this is due to cloudfront cache invalidation. You have a _very_ short cacheDuration set (300 seconds, ie 5 mins), which will make the Imager cache refresh every five minutes. When it does, it will re-upload the transformed asset to AWS, _and run a cloudfront cache invalidate API call_ (which is needed if the transform has actually changed). So there will be a ton of invalidation requests at $0.005 each. Not sure how many transforms you have, but say that you have 10 transforms (which is not much, but other caching would keep this from happening, so) that are being invalidated every five minutes, that's $144 right there. 😬

This is just a guess though, but I would recommend bumping that cacheDuration up significantly anyway. And maybe check the details of the pricing reports, what that cost is actually from. Been a long time since I used AWS regularily, but I seem to recall that you can get it split into bandwidth, storage, api calls, etc, right?

**Comment by Brijeshgrg1999** [comment]
@aelvan  Thank you for the insight ,  regarding the cacheDuration , what is the optimal duration that I should be implementing ?

**Comment by aelvan** [comment]
The default value is `false`, which means that it'll never expire unless you delete it manually. In most cases this is completely fine, at least if you primarily transform Assets. If an asset is changed, the cache will automatically be broken. If you deal with alot of external images that may change, it may be necessary with a shorter cacheDuration. But this can also be overridden at the template level so that you can deal with at on a case by case basis. 

Would be interesting to hear back if this was indeed the issue.

**Comment by Brijeshgrg1999** [comment]
@aelvan  Thank you for the reply , I can see the cost of the cloudfare to drop significantly after I changed my cacheDuration to a week , I believed that was the issue for high cost . Thanks for the help !!!

**Comment by aelvan** [comment]
Great, glad we got that sorted out! :)
