### ISSUE TITLE
Falling to generate image transform with fallback image override

### ISSUE THREAD

**Issue by anita-chouhan** [spacecatninja/craft-imager-x#268]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
1. Add the code snippet to a twig file to generate transforms:
`craft.imagerx.transformImage(externalImageLink, {}, {}, { cacheDurationRemoteFiles: 60 * 60 * 24, fallbackImage: 'https://placehold.co/600x400.png' })`

### Description
I am trying to generate image transforms for an external image. I want to override the `fallbackImage` parameter for it. I am expecting the fallback image to render if the external image URL is invalid, but currently it is throwing an error. 

### Displayed errors, stack trace, relevant logs  
<img width="950" alt="Screenshot 2024-06-24 at 5 49 15 PM" src="https://github.com/spacecatninja/craft-imager-x/assets/30666052/9f15130e-d168-4114-aa97-312fdb05b539">

### Additional info

- Imager version & edition: Imager X Lite version 4.4.0
- Craft version: 4.8.9
- PHP version: 8.0.2
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.1-23)

**Comment by aelvan** [comment]
This should be fixed, it was due to the slashes in the config override making it into the transform filename, which broke the path. Let me know if this didn't help.

Also, I would recommend adding those kinds of config settings to you config, unless you actually need to change them at the template level.
