### ISSUE TITLE
Feature Request: Utilities Page Tool

### ISSUE THREAD

**Issue by clarknelson** [spacecatninja/craft-imager-x#29]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
I would love to have some sort of option in the control panel to build the assets based on `config/imager-x-transform.php`! Pro feature possibly?

![image](https://user-images.githubusercontent.com/4106671/84169777-a4ee5b00-aa3e-11ea-8c83-f7ff1928a0ab.png)

**Comment by aelvan** [comment]
That's doable. I was actually thinking of making a utility for getting information about the environment (image driver, versions, optimizers, etc) to help with configurating and debugging. An interface for generating transforms could be part of it.

How do you envision it working? The possibility of choosing volumes/folders and selcting transforms to run on them? Any usage pattern you'd find extra helpful?

**Comment by clarknelson** [comment]
I would love for it to work just like the "Updating asset index" page, where it list all of asset sources, maybe there is a 2nd column with the transform names. 

![image](https://user-images.githubusercontent.com/4106671/84193882-c3198280-aa61-11ea-922b-8227d4bfbaea.png)

Some logging and debugging would be great too, i'm sure you are aware of the system report page. Pretty open but it would be be great for clients / convivence.

**Comment by aelvan** [comment]
This was added in v3.1.0.

Let me know if you have any comments or questions!

**Comment by clarknelson** [comment]
Wow thank you so much! What a great utility. Do you have a tip jar?

**Comment by clarknelson** [comment]
It looks like the first volume runs but the next volume selected doesn't run. Adding all the asset volumes only adds the first one it seems :)

**Comment by aelvan** [comment]
Ooops, let me have a look!

**Comment by aelvan** [comment]
Silly mistake, it's fixed in 3.1.1.

**Comment by natebeaty** [comment]
Am I mistaken, or is the ability to clear out Imager X transforms via utility menu not available in the Lite edition? If so, is there no way to delete old transforms if you pay $49 for Lite?

**Comment by aelvan** [comment]
@natebeaty The ability to clear caches is not tied to editions. 

This original FR was concerning adding a utility to generate transforms through the control panel, not clearing caches. In the new utility for the Craft 4 version, this was added. 

For Craft 3, cache clearing was done through the native clear cache utility in Craft, until Imager X 3.6 which disabled this by default, because alot of people were accidentally clearing the Imager cache by doing `craft clear-caches/all`. You can bring the old functionality back by setting the `registerCacheOptions` config setting to `true` in `imager-x.php`. There are also [controller actions](https://imager-x.spacecat.ninja/controller-actions.html) to do it, or you can just empty the imagerSystemPath manually.

Hope that helps?

**Comment by natebeaty** [comment]
Oh! That explains it, as I still haven't upgrade to Craft 4 on this project. `registerCacheOptions` was the magic I was looking for, and understandable why that was moved to a configurable option. Sorry for the noise.
