### ISSUE TITLE
Function Imagick::setimageclipmask() is deprecated

### ISSUE THREAD

**Issue by brandondeweese** [spacecatninja/craft-imager-x#34]
### I'm submitting a... 

- [X ] bug report
- [ ] feature request
- [ ] general question

Function Imagick::setimageclipmask() is deprecated. 

You can see it here: www.scale.rocks. The error happens on both imager and imager-x. 

- Imager version & edition: Imager X | v3.0.11
- Imager transformer:  Craft
- Craft version: Craft Pro 3.4.25
- PHP version:  7.4.3
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.9.10-23)
- Database driver & version: MySQL 8.0.20

**Comment by aelvan** [comment]
Hi,

This is a know issue that doesn't have a resolution due to how some things were deprecated in Imagick 3.4.4, see some related issues [here](https://github.com/aelvan/Imager-Craft/issues/279) and [here](https://github.com/aelvan/Imager-Craft/issues/256) (P&T later rolled back that update that's mentioned, so it didn't get resolved). 

The only possible solutions are to either 1) revert to Imagick 3.4.3 with ImageMagick 6.x or compile Imagick based on ImageMagick 7.x, or 2) recreate the effect you want using something other than the ColorBlend effect (I assume that's what's causing the error since it's the only place in Imager that `setimageclipmask` is used).
