### ISSUE TITLE
Use environment variable for google cloud storage auth file

### ISSUE THREAD

**Issue by chanwhab** [spacecatninja/craft-imager-x#38]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
 
If we are using google cloud storage, we have to upload the key to some public available location.
Can we use similar solution like craftcms/google-cloud (to use .env to store the key)
https://imager-x.spacecat.ninja/configuration.html#general-configuration
https://github.com/craftcms/google-cloud
https://github.com/craftcms/google-cloud/issues/12

### Displayed errors, stack trace, relevant logs  

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

- Imager version & edition:
- Imager transformer:
- Craft version:
- PHP version:
- Image driver & version:
- Database driver & version:
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Thanks for submitting, I'll have a look at implementing it.

**Comment by aelvan** [comment]
This was added in v3.1.5. 

You can now use environment variables in the `keyFile` config setting, and the value can be either the path to a key file (as before), or the json contents of the key file. When adding the contents to your .env file, remember to escape the `\n` characters in the file, to `\\n`, since `\` is an escape character in .env file strings.
