### ISSUE TITLE
Syntax Question

### ISSUE THREAD

**Issue by webtrend** [spacecatninja/craft-imager-x#4]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
I have a couple of questions related to syntax.
Transform the Transform does not work in the following case 
```
{% set transformedImage = craft.imager.transformImage(asset, 'blogThumbnail') %}
                                {% if craft.imager.serverSupportsWebp() %}
                                    {% set transformedImagesWebp = craft.imager.transformImage(transformedImage, { format: 'webp' }) %}
                                {% endif %}
```
It throws an error. I am using remote AWS storage so I am wondering if the image object is stored locally. My local cache folder is always empty so I am not sure if it is even used. So I would expect an error in a case if there is no local storage. What can I do to prevent this error.

Another question:

When I use a named transform from imager-x-transforms.php, the resulting object is an array even when there is only 1 image. So when I want the url, I have to do this:
`transformedImage[0].url `
Is it the correct way to call the url of the object? I tried `transformedImage.url` but it does not work. 

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

- Imager version and edition: 3.0
- Craft version:3.4.5
- PHP version:7.2
- Database driver & version:
- Plugins & versions:

**Comment by aelvan** [comment]
Hi,

Let's start with this one:

> When I use a named transform from imager-x-transforms.php, the resulting object is an array even when there is only 1 image.

If you pass in an array, with only one transform in it, to the `transforms` parameter in a named transform, it will indeed return an array with one transformed image in it. You can return an object by passing a single array/object to the parameter, like this:

```
'singleTransform' => [
    'transforms' => [
        'width' => 1200
    ]
],
```

This is maybe a bit counter-intuitive because the named transform parameter is called `transforms` (plural). But it's the equivalent of how the `transformImage` method usually works, ie:

```
{# Returns a single transforms image model  #}
{% set transformed = craft.imager.transformImage(image, { width: 1200 }) %}
{{ 'URL: ' ~ transformed.url }}

{# Returns an array with one single transforms image model as the only item in it  #}
{% set transformed = craft.imager.transformImage(image, [{ width: 1200 }]) %}
{{ 'URL: ' ~ transformed[0].url }}
```

And as you can see, if it's an array you get back, you need to access it like `transformed[0]`, or loop over it.

> Transform the Transform does not work in the following case

What's the error message you get? If the issue is that the first transform returns an array, try `{% set transformedImagesWebp = craft.imager.transformImage(transformedImage[0], { format: 'webp' }) %}` instead.

> My local cache folder is always empty so I am not sure if it is even used. So I would expect an error in a case if there is no local storage. 

This sounds a bit suspicious. You should find the transformed images in your `imagerSystemPath`, even if you're using an external storage to upload to. And this is the location that Imager will load the image from, if you're transforming a transform. 

Have you checked your logs? If the upload to external storages fail, Imager will delete the file in the `imagerSystemPath`, so that Imager will try to recreate and upload it on next request. if there's something wrong with your aws setup, that might be the root cause of all of these issues. It might be a good idea to temporarily disable aws to see if that's the issue.

Have a look at [the troubleshooting page in the docs](https://imager-x.spacecat.ninja/troubleshooting.html) for some hints on how to check the logs.

And as a sidenote; instead of transforming the thumbnail, and then doing a new transform on that image to create the webp image, I'd rather just do the webp transform from the source image. The way you're doing it will speed things up, but the quality will suffer, because you're recompressing the image 3-4 times.

**Comment by aelvan** [comment]
Hi @webtrend, did you sort this out?
