### ISSUE TITLE
mozjpeg optimization results in an empty file

### ISSUE THREAD

**Issue by JoshCoady** [spacecatninja/craft-imager-x#53]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Config for mozjpeg optimizer
2. do a transform

### Description
 
Mozjpeg does not allow you to have the same input and output files. See https://github.com/mozilla/mozjpeg/issues/248 . It results in the input file being emptied and the optimization failing with the error message "Empty input file".

### Displayed errors, stack trace, relevant logs  

```
2020-09-23 21:47:37 [-][1][-][info][application] Command "/usr/local/bin/cjpeg -outfile "/var/app/web/imager-x/images/2366/30568-044635_0066f46bde.jpg" "/var/app/web/imager-x/images/2366/30568-044635_0066f46bde.jpg"" returned "Empty input file"
    in /var/app/vendor/spacecatninja/imager-x/src/optimizers/MozjpegOptimizer.php:37
    in /var/app/vendor/spacecatninja/imager-x/src/jobs/OptimizeJob.php:60
    in /var/app/vendor/craftcms/cms/src/queue/Queue.php:121
```

### Workaround

If I replace this config:
```
            'path' => '/usr/local/bin/cjpeg',
            'optionString' => '',
```

With the following it works as expected.
```
            'path' => '/bin/sh',
            'optionString' => '/var/app/mozjpeg.sh',
```
/var/app/mozjpeg.sh:
```
#!/bin/sh
set -e

# the infile is the last param, so make it the first param to make it easier to find and remove
count=0
until test $((count+=1)) -ge $#
do
  set -- "$@" "$1"
  shift
done

infile=${1-}
shift $((!!$#))

tempfile=$(mktemp)
trap "rm -f $tempfile" 0 2 3 15
mv "$infile" "$tempfile"
/usr/local/bin/cjpeg "$@" "$tempfile"
```

### Additional info

- Imager version & edition: 3.2.1 pro
- Imager transformer: mozjpeg
- Craft version: 3.5.8
- PHP version: 7.4
- Image driver & version:
- Database driver & version:
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Hi,

The mozjpeg optimizer wasn't made to be used with the cjpeg runtime. As the thread you linked to says, it's only a demo tool, not intended for production work. Rather, it's intended to be used with a compiled version of the library where it acts as the encoder for jpegtran. See [this article for more info](https://nystudio107.com/blog/installing-mozjpeg-on-ubuntu-16-04-forge).

Also, since it's a drop-in replacement for jpegtran, having a separate optimizer for this is kinda redundant, but [I didn't realize until after implementing the FR](https://github.com/aelvan/Imager-Craft/issues/49), so... it's there.

**Comment by JoshCoady** [comment]
Thanks for clearing that up. The docs said that mozjpeg had better results, but the link there goes to the project page which links to https://calendar.perfplanet.com/2014/mozjpeg-3-0/ which has examples using cjpeg. I also googled it an the articels I found used cjpeg as well, sometimes symlinking mozjpeg to it. Anyway, thanks again for the article. Looks like that is my path forward.
