### ISSUE TITLE
External URL doesn't work

### ISSUE THREAD

**Issue by Coysh** [spacecatninja/craft-imager-x#57]
Using the eventbrite API returns an image with a weird format (for example: `https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F114238709%2F458569053688%2F1%2Foriginal.20201010-120223?auto=format%2Ccompress&q=75&sharp=10&s=73b600442de481cbfa3be17b8f798c25`)

Using this URl doesn't work, but a normal image URL (``) does.

### I'm submitting a... 
- [X] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
1. Use `https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F114238709%2F458569053688%2F1%2Foriginal.20201010-120223?auto=format%2Ccompress&q=75&sharp=10&s=73b600442de481cbfa3be17b8f798c25`
2. Transform fails

**Comment by aelvan** [comment]
There're so many different ways URL's can be encoded, so Imager tries to fix some of the most common issues. Unfortunately, with complex url's like this, where you have an encoded url inside an url, it sometimes fail. 

As of v3.2.3, there is a `useRawExternalUrl` config setting that can be turned off to opt out of all the encoding that Imager does by default, which works with your url because it's already been prepped.

**Comment by Coysh** [comment]
Hi @aelvan thanks so much! That fixed one issue, but still having another image - it's obviously recognising the .20201010-120223 as the file extension:

![image](https://user-images.githubusercontent.com/5764356/95691825-1ec76880-0c1a-11eb-8fb5-27c5846ded17.png)
