### ISSUE TITLE
[FR] Support for Blurhash

### ISSUE THREAD

**Issue by davidhellmann** [spacecatninja/craft-imager-x#67]
Hey,

came across this few weeks ago and today again: https://github.com/woltapp/blurhash
For me looks like a great feature to level up placeholder images. 

Maybe it's integratable into imager-x

**Comment by aelvan** [comment]
Looked into this, but will not integrate BlurHash for now, mostly because it requires PHP 7.2, which is currently higher than what Craft CMS supports. When the next version ships and the requirements are bumped, I'll revisit.

I'll also note that BlurHash is mostly useful as an intermediate format for when you want to create the image on the client using for instance JS or in a native app. Decoding it into the final placeholder from PHP/Twig, doesn't make much sense as what you'd get back would be the generated bitmap image, ie the same as you would with the placeholder functions that are there today. But, when using Craft in a headless context, it could save a lot of bandwidth.

**Comment by aelvan** [comment]
This has been added in v3.4.0 which is just out. 

You can get the encoded string through the `getBlurhash()` method on a transformed image, or by using `blurhash` as [format on the imagerTransform GraphQL directive](https://imager-x.spacecat.ninja/usage/graphql.html).

**Comment by ursbraem** [comment]
Hey! I want to try it but can't find it in the docs.


`{% set transformedImage = craft.imager.transformImage(block.image.one(), { width: 500 }, { ratio: 6/4, position: '100% 100%', jpegQuality: 80 } )%}
`
then either 

`{% set blurHash = transformedImage.getBlurhash() %}`

-> results in a error 500

`{% set blurHash = craft.imagerx.getBlurhash(transformedImage) %}`

-> results in `Neither the property "getBlurhash" nor one of the methods "getBlurhash()", "getgetBlurhash()"/"isgetBlurhash()"/"hasgetBlurhash()" or "__call()" exist and have public access in class "spacecatninja\imagerx\variables\ImagerVariable".`

Imager-x version is 4.1.6 (Lite, trial currently)

**Comment by ursbraem** [comment]
Ah. I get it. `{% set blurHash = transformedImage.getBlurhash() %}` is correct. The source image (I cheated in the code above) was too big.
