### ISSUE TITLE
Override named transforms config

### ISSUE THREAD

**Issue by pl-mnm** [spacecatninja/craft-imager-x#7]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

Is it possible to override settings in the named transforms config when calling it from a template?

This is my use case: I have a an image for which I'm already generating two sets of transforms, one portrait for narrow screens and another landscape for larger screens:

```
// imager-x-transforms.php

return [
  'image' => [
    'transforms' => [
      ['width' => 600],
      ['width' => 1200]
    ],
    'defaults' => [
      'ratio' => 3/4
    ],
    'configOverrides' => [
      'fillTransforms' => true
    ]
  ],
  'image-desktop' => [
    'transforms' => [
      ['width' => 600],
      ['width' => 1600]
    ],
    'defaults' => [
      'ratio' => 16/9
    ],
    'configOverrides' => [
      'fillTransforms' => true
    ]
  ],
];
```
I'd now like to generate WebP variants as well, without having to duplicate all of this.

Is it possible to alter one transform setting (e.g. `format`) when passing the config transform handle? Is there a better way to achieve this?

Thanks in advance.

**Comment by aelvan** [comment]
Hi,

Yes, you can still add defaults and config overrides to the `transformImage` method in your templates, even if you use named transforms. For example:

```
{% set transforms = craft.imager.transformImage(image, 'image', { format: 'webp' }) %}
```

But, _please note_, if you use the auto generation feature, that wouldn't know about the variants that you specify in your templates, so you wouldn't get those generated. 

This got me thinking, can named transforms be used inside named transforms...? Turns out, they couldn't, but that was just because I hadn't thought of it. I added the functionality and pushed a new version now (3.0.2) that has support for it. So, if you update, you can do:

```
return [
  ...
  'imageWebP' => [
    'transforms' => 'image',
    'defaults' => [
      'format' => 'webp'
    ]
  ],
  ...
]
```

Hope this helps!

**Comment by pl-mnm** [comment]
Thanks a lot, that second option worked like a charm!
