### ISSUE TITLE
Transforms seem to expire and need reprocessing (possibly cacheDurationExternalStorage?)

### ISSUE THREAD

**Issue by alexwybraniec** [spacecatninja/craft-imager-x#72]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [X ] general question

### Steps to reproduce

1. Craft site using Imager X
2. (Seemingly) every 14 days page requests with lots of images cause the site to become overloaded

### Description
Hello,

I'm trying to understand why our transformed images that are uploaded to S3 seem to need re-transforming occasionally.

This is for a new site, so I'm still trying to understand the causes, but it appears that it might be caused by cacheDurationExternalStorage being reached?

My question is... why do transforms that have already happened, and are stored remotely need to be re-transformed? Is there a better set of cache related config settings for files that, once transformed, should never need to be transformed again (unless they are changed in the admin)?

### Additional info

- Imager version & edition: v3.2.4 Pro
- Imager transformer: craft
- Craft version: Craft CMS 3.5.14 Pro
- PHP version: 7.4.11
- Image driver & version: GD 7.4.11
- Database driver & version: MySQL 5.5.5

**Comment by aelvan** [comment]
Hi,

`cacheDurationExternalStorage` is not relevant in this case, that's just used to set the cache headers that are sent from the external storage service (S3 in this case) when the transformed images are requested by the client. 

What kind of hosting and deploy routines do you use? Even if the transformed files are uploaded to an external storage, the generated files in `imagerSystemPath` is used as the cache to determine if a transform is generated or not, and if it needs to be generated (base on the file timestamp and `cacheDuration`). If the files gets wiped for some reason, the transforms need to be re-generated, even if the transformed files still exist on the external storage.

Another thing to look into is `cacheDurationRemoteFiles`. This one is used for the cache that stores files downloaded from external url's. Or, if you pass in an url for a local image instead of the asset itself:

```
{# Don't do this! #}
{% set transforms = craft.imager.transformImage(someAsset.url, { width: 1200 }) %}

{# Do this! #}
{% set transforms = craft.imager.transformImage(someAsset, { width: 1200 }) %}
```

**Comment by alexwybraniec** [comment]
Hello, sorry for the slow reply.

We are doing transforms like this...
`craft.imagerx.transformImage(img, 'cardImage')`
...so it's not your last point.

Would there be side effects if we set cacheDuration to a very very large number? Is it possible to disable the cache from expiring ever?

As for hosting and deploy routines, we're using DeployHQ to auto deploy to a Digital Ocean VM. We do some permissions juggling with chmod/chown but that doesn't affect the imager directory.

**Comment by aelvan** [comment]
Ok, so DeployHQ has support for zero downtime deployments/atomic deploys, are you using that? If that's the case, make sure that your `imagerSystemPath` is in a shared location. If it's not, it would be wiped every time you deploy.

**Comment by aelvan** [comment]
Closing. Please open a new issue if the problem persists.
