### ISSUE TITLE
Target assets within super table fields

### ISSUE THREAD

**Issue by daniellelecomte** [spacecatninja/craft-imager-x#75]
I'm submitting a... 
- [ ] bug report
- [x] feature request
- [ ] general question

Would it be possible to access asset fields within a **super table field** in the same way that you can within a matrix when defining elements to auto-generate?

`<superTableFieldHandle>:<superTableTypeHandle>.<fieldHandle> `

And if so, could you also target an asset in a nested matrix within a super table? (I know this one may be a stretch lol)

`<superTableFieldHandle>:<superTableTypeHandle>.<matrixfieldHandle>:<matrixTypeHandle>.<fieldHandle> `

Thanks!
Danielle

**Comment by aelvan** [comment]
SuperTable fields are now supported, but you need to use the (new) wildcard type syntax because SuperTable fields doesn't have block types. So something like `mySuperTableField:*.image`.

I didn't manage to wrap my head around a solution that would make it possible to nest further down. But, it's worth nothing that Matrix and SuperTable blocks are elements in much the same way as Entries, Categories, etc. So inside the `'elements'` key, you can target them exactly as you would other elements. For instance:

```
'elements' => [
    [
        'elementType' =>  \craft\elements\MatrixBlock::class,
        'criteria' => [
            'fieldId' => 11,
            'type' => 'media'
        ],
        'fields' => ['images'],
        'transforms' => ['myImage']
    ]
],
[
        'elementType' =>  \verbb\supertable\elements\SuperTableBlockElement::class,
        'criteria' => [
            'fieldId' => 28
        ],
        'fields' => ['image'],
        'transforms' => ['heroImage']
    ]
```

Annoyingly, you have to use the field ID to target a specific field (you don't have to, you could target all matrix blocks, or all matrix blocks of a certain type) as shown above, you can't use the field name. 

And, _I assume_ that you could for instance use the `<matrixfieldHandle>:<matrixTypeHandle>.<fieldHandle>` syntax inside either of those, but I haven't taken the time to test that. I suspect that most of the time one could get away with targeting different elements in a more granular way.

Let me know your thoughts on this if you think there's something that needs to be improved!

**Comment by daniellelecomte** [comment]
Thanks!!
