### ISSUE TITLE
Difference with transform parameters?

### ISSUE THREAD

**Issue by jamesmacwhite** [spacecatninja/craft-imager-x#8]
### I'm submitting a... 
- [ ] bug report
- [ ] feature request
- [X] general question

### Description

Have the transformer parameters changed between Imager and Imager-X at all? I have a macro that applies a transformer config of the following (in addition to the provided width and height for each image).

```
{% set sharedConfig = {
    mode: 'fit',
    quality: 95,
    position: config.image.focalPoint|default('center center')
} %}

{% set resizedImages = craft.imager.transformImage(images, sizes, sharedConfig) %}
```
However it doesn't look like they are working. They seem to be falling back to the defaults of, crop mode, quality of 80 (set as a default in `config/imager-x.php`).

If I update `mode:` to `fit:` and `quality:` to `q:` they seem to work, but this doesn't seem the same as the documentation.

https://imager-x.spacecat.ninja/transform-parameters.html

Forgive me if I'm going crazy!

### Additional info

- Imager version and edition: 3.0.2
- Craft version: 3.3.20.1
- PHP version: 7.2
- Database driver & version: MySQL 5.6
- Plugins & versions: N/A

**Comment by aelvan** [comment]
It's not suppose to have changed, so I'll have to look into that. What transformer are you using, craft or imgix?

**Comment by jamesmacwhite** [comment]
Sorry, should have stated that originally! Transformer is Imgix.

**Comment by aelvan** [comment]
Hi @jamesmacwhite. I've tested now, and can't really find anything wrong, or any difference from Imager 2.0. A couple of things though:

`quality` isn't really an Imager transform parameter, and never was. I built in a fallback where using it would translate it to `jpegQuality`, in case someone used the it (since it's a Craft transform parameter). That might just have made things more confusing, I guess. In Imager, you're suppose to use `jpegQuality`, `pngQuality` and `webpQuality`. It's more verbose, but adds a greater degree of flexibility (mainly because since jpeg and png quality is two completely different things).

So, could it be that the image you're testing with maybe is an png image? That would explain why `quality` doesn't do anything, it'd fallback to the pngQuality and translate this to the Imgix equivalent.

Passing `q` to the transform will always override the `q` parameter in the URL for the Imgix transformer (they use that for all types of images). It might be a bit cleaner to use the Imager-parameters because it'll allow you to switch transformers later. But, your call.

Not sure what's going on with the `mode` parameter though. If you have `mode: 'fit'`, what does that translate to in the URL that Imgix returns? Also, what other parameters are you passing in? Have you tried to make a reduced test case, eliminating the macro and doing the transform directly?

Again, you can pass `fit` to the transform parameters, but not recommended for the same reasons as above.

**Comment by jamesmacwhite** [comment]
@aelvan Hi, thanks for testing this. Interesting about the quality parameter. I guess because of the fallback, it's been something I've always used and figured it was a transformer.

So in terms of setting quality related transformers, it's worth called the jpeqQuality, pngQuality, webpQuality parameters for setting the quality to be flexible if (probably unlikely) we'd drop Imgix, so they can be translated to Craft and not break?

Setting `mode: fit` sets ?fit=clip` in the URL under Imgix, not 'crop', I must have misread that on Friday is that technically being translated correctly in this case?

**Comment by aelvan** [comment]
> So in terms of setting quality related transformers, it's worth called the jpeqQuality, pngQuality, webpQuality parameters for setting the quality to be flexible if (probably unlikely) we'd drop Imgix, so they can be translated to Craft and not break?

Yes, that would make it easier to switch to Imager's **craft transformer**. But if you by "Craft" means **native Craft transforms**, ie. your macro can be used for both, it'd maybe make sense to use `quality`. But, these are minor details I guess. 

> Setting mode: 'fit' sets ?fit=clip` in the URL under Imgix, not 'crop', I must have misread that on Friday is that technically being translated correctly in this case?

Yes, `?fit=clip` is the equivalent of `mode: 'fit'` in Imager/Craft.
