### ISSUE TITLE
Using ImgIx triggers volume error

### ISSUE THREAD

**Issue by jripmeester** [spacecatninja/craft-imager-x#88]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
1. Configure ImgIx Source for Imager X
2. Place image on a page and visit page

### Description
The transform triggers an error 
Call to undefined method spacecatninja\imagerx\models\ImgixTransformedImageModel::getVolume()

### Displayed errors, stack trace, relevant logs  
https://ghostbin.com/paste/nZkFO

### Additional info

- Imager version & edition:  v3.3.0 Pro
- Imager transformer: ImgIX
- Craft version: Craft CMS 3.6.4.1
- PHP version: 7.3

**Comment by aelvan** [comment]
Hi, 

By the looks of it, you're passing in an `ImgixTransformedImageModel` (ie, an already transformed image) to the `transformImage` method. Based on the stack trace, it looks like the offending code is this:

``` 
{% set transformedImages = craft.imager.transformImage(image, size) %}
{% set placeholder = craft.imager.transformImage(transformedImages[0], { width: transformedImages[0].getWidth()/4, height:transformedImages[0].getHeight()/4, format: 'jpg', bgColor: '#FFFFFF', jpegQuality: 2 }) %}
```

Here you're passing in a transformed image with `transformedImages[0]`. That would actually work with the default craft transformer (maybe you migrated from using that?), but not with Imgix since it can't really transform an Imgix URL itself. You could actually set up a web proxy source, a separate Imgix profile, and switch profile when doing the second transform, but... A lot of hazzle, it's probably easier to just create the placeholder based on the original image itself and calculate the width and height based on the size directly.

**Comment by aelvan** [comment]
@jripmeester Did this resolve your issue?

**Comment by jripmeester** [comment]
Hi @aelvan, yes i did. I've added the original image to the placeholder creation.
Thank you for pointing out my error.

Loving Imager X! It's probably the most complete image manipulation plugin Craft will ever need!

**Comment by aelvan** [comment]
Good to hear, thanks! :)
