### ISSUE TITLE
Using imgix but still cache in storage/runtime/imager?

### ISSUE THREAD

**Issue by WHITE-developer** [spacecatninja/craft-imager-x#95]
### I'm submitting a... 
- [ ] bug report
- [ ] feature request
- [x] general question

### Description
We use imager-x as "api" for imgix. We see that there is still imager cache in the storage/runtime/imager folder. Is that normal and if so, why? All transforms are served from imgix so doesn't sound logical for me that it is also storing in the storage folder.

### Additional info

- Imager version & edition: Pro 3.3.0
- Imager transformer: imgix
- Craft version: 3.5.19.1
- PHP version: 7.4.15

**Comment by aelvan** [comment]
Hi,

That _depends_. :) 

If you're only transforming Assets, there shouldn't be anything stored in that folder. If you're transforming external images, or pass in assets by url, the image could be downloaded _if_ `getExternalImageDimensions` in the Imgix profile is set to `true` (default), and width _and_ height cannot be determined by the transform. Like, if you only pass in width to the transform and not height or ratio. Then the original file will be downloaded so that Imager can get the original size, and calculate the missing dimension. You can set `getExternalImageDimensions` to `false` to avoid this, but then the missing dimension will be 0 so make sure your code doesn't rely on both dimensions. 

There also is other functionality in Imager, like placeholders and color analysis, that is not run through Imgix and will require an asset to be temporarily downloaded if you use them.

So, does any of those sound like scenarios that you have in your project?

**Comment by WHITE-developer** [comment]
Thanks for the info.
Yes, seems that some of the transforms didn't have all the dimensions, going to fix that in our project. Good to know.
