### ISSUE TITLE
Broken Purging

### ISSUE THREAD

**Issue by clsse** [spacecatninja/craft-imager-x#98]
Hi Andre,

We spoke a while back about broken purging. I finally got around to trying your updated ImgixService.php solution and followed your steps outlined below:

> Could you try unzipping the attached zip file and replacing the php file with the same name in the /vendor/spacecatninja/imagerx/src/services folder, in an environment that is running in devMode (and preferably where you can revert the changes easily afterwards). It contains two log statements that outputs the payload sent to Imgix, and the result that comes back.
> 
> Navigate to Assets in the control panel. Delete the /storage/logs/web.log file. Select an asset and choose "Purge Imgix" from the context menu. Open the newly created /storage/logs/web.log file and search for ImgixService::purgeUrlFromImgix. There should be a couple of log entries.
> 
> Either paste those here, or send them to me at hi@spacecat.ninja if you feel that it's too sensitive (it doesn't contain anything really sensitive, but).
> 
> ImgixService.php.zip

This is the output I got in the web.log:

```
2021-03-26 19:12:53 [-][1][-][info][spacecatninja\imagerx\services\ImgixService::purgeUrlFromImgix] {"data":{"attributes":{"url":"https:\/\/wold.imgix.net\/images\/Global\/Placeholders\/placeholder-5.jpeg"},"type":"purges"}}
2021-03-26 19:12:55 [-][1][-][info][spacecatninja\imagerx\services\ImgixService::purgeUrlFromImgix] {
  "data": {
    "attributes": {
      "purge_id": "c3dfaa37-a3bc-4d93-8fcb-b1b6fa887ca7"
    },
    "id": "c3dfaa37-a3bc-4d93-8fcb-b1b6fa887ca7",
    "type": "purges"
  },
  "included": [],
  "jsonapi": {
    "version": "1.0"
  },
  "meta": {
    "authentication": {
      "authorized": true,
      "clientId": null,
      "mode": "PUBLIC_APIKEY",
      "modeTitle": "Public API Key",
      "tag": "info@authenticff.com",
      "user": null
    },
    "server": {
      "commit": "3cf79386",
      "status": {
        "healthy": true,
        "read_only": false,
        "tombstone": false
      },
      "version": "3.145.2"
    }
  }
}
```

**Comment by aelvan** [comment]
Looks like everything works as it should, the response from Imgix indicates that the purge was successful. The url in the first log entry is the one that you expected to be purged?

I don't remember everything we went through in the last thread, but considering that the purge goes through successfully, if you don't see the updated image afterwards it's due to one of two things: 1) the old transform is cached in your browser or some cache on your local network, or 2) a race-condition is happening where a transform for the old image is requested and cached before the purge goes through on Imgix. 

Hard to tell which it is, and I'm not sure how to help you debug this further, sorry.
